### ISSUE TITLE
Remove sensu_asset metadata parameter (sensu2)

### ISSUE THREAD

**Issue by treydock** [sensu/sensu-puppet#1005]
Upstream removed metadata from assets (https://github.com/sensu/sensu-go/pull/2273).  Need to update sensu_asset type to account for this change.

**Comment by treydock** [comment]
So this relates a little to #1006 but upon looking it seems the `metadata` property was replaced by `metadata` hash now used also by `check` and `entity` which means arbitrary key/values for `labels` and `annotations` will be possible with assets.

**Comment by ghoneycutt** [comment]
@treydock can this be closed now that https://github.com/sensu/sensu-puppet/pull/1013 is merged?

**Comment by treydock** [comment]
Yep, closing.
