### ISSUE TITLE
Replace environment & organization with namespace for sensu2 types

### ISSUE THREAD

**Issue by treydock** [sensu/sensu-puppet#1006]
All types that use environment and/or organization will need to be updated to use namespaces.  Also flags passed to sensuctl will need to be updated.

Upstream change: https://github.com/sensu/sensu-go/pull/2254

**Comment by ghoneycutt** [comment]
@treydock can this be closed now that https://github.com/sensu/sensu-puppet/pull/1013 is merged?

**Comment by treydock** [comment]
Yep, closing.
