### ISSUE TITLE
Remove or update extended_attributes for sensu2 types

### ISSUE THREAD

**Issue by treydock** [sensu/sensu-puppet#1008]
Upstream replaced extended attributes with labels.  This will impact `sensu_check` and `sensu_entity` at the very least.

Upstream change: https://github.com/sensu/sensu-go/pull/2283

**Comment by treydock** [comment]
Looks like this is now what we get:

```
[
  {
    "command": "check-cpu.sh -w 75 -c 90",
    "handlers": [],
    "high_flap_threshold": 0,
    "interval": 60,
    "low_flap_threshold": 0,
    "publish": true,
    "runtime_assets": [],
    "subscriptions": [
      "linux"
    ],
    "proxy_entity_id": "",
    "check_hooks": null,
    "stdin": false,
    "subdue": null,
    "ttl": 0,
    "timeout": 0,
    "round_robin": false,
    "output_metric_format": "",
    "output_metric_handlers": [],
    "env_vars": null,
    "metadata": {
      "name": "check-cpu",
      "namespace": "default",
      "labels": null,
      "annotations": null
    }
  }
]
```
This will have to be bundled with #1006 since the `metadata` key for both `sensu_check` and `sensu_entity` is what holds the `namespace` value.

**Comment by ghoneycutt** [comment]
@treydock can this be closed now that https://github.com/sensu/sensu-puppet/pull/1013 is merged?

**Comment by treydock** [comment]
Yep, closing.
