### ISSUE TITLE
Update sensu2 to replace id properties with name

### ISSUE THREAD

**Issue by treydock** [sensu/sensu-puppet#1012]
Upstream is changing references to `id` with `name` and this will require some changes to several types.  Also appears like the `metadata` key will be used for `name` and `namespace` combinations and this will also require some logic changes for most types.

Upstream PR: https://github.com/sensu/sensu-go/pull/2308

**Comment by ghoneycutt** [comment]
Fixed by https://github.com/sensu/sensu-puppet/pull/1013
