### ISSUE TITLE
Fix sensu2 extension list for all namespaces

### ISSUE THREAD

**Issue by treydock** [sensu/sensu-puppet#1014]
Upstream fixed `sensuctl extension list` to support `--all-namespaces`.  This will need to be applied in #1013.  This is one item mentioned in #901 

Upstream fix: https://github.com/sensu/sensu-go/pull/2337

**Comment by ghoneycutt** [comment]
@treydock can this be closed now that https://github.com/sensu/sensu-puppet/pull/1013 is merged?

**Comment by treydock** [comment]
Yep, closing.
