### ISSUE TITLE
Rewrite RBAC handling for sensu2

### ISSUE THREAD

**Issue by treydock** [sensu/sensu-puppet#1016]
There is a PR in sensu-go, https://github.com/sensu/sensu-go/pull/2338, that will require large changes to `sensu_role`, likely a rewrite.  Also new types will be needed:

* cluster-role
* cluster-role-binding
* role-binding

May be able to combine the binding resources into parent resources for simplicity, will have to evaluate that option.

**Comment by treydock** [comment]
Docs already updated to reflect RBAC changes: https://docs.sensu.io/sensu-go/5.0/reference/rbac/

**Comment by treydock** [comment]
@ghoneycutt The `rules` property prototype I have validates the data structures are correct types of does not validate values.  Should we validate values, like `verbs` are valid? https://docs.sensu.io/sensu-go/5.0/reference/rbac/#role-attributes

**Comment by ghoneycutt** [comment]
I dont think we want to validate each of the acceptable values and this makes the coupling very tight and when changes are made to sensu, they will not be accessible until we make changes.

**Comment by treydock** [comment]
Sounds good, current validation is just data types so that things like `subjects` are Array of Hashes and the Hash keys match valid keys since determines data structure used by provider.

**Comment by treydock** [comment]
Closing via #1017
