### ISSUE TITLE
sensu_api_validator fails when Backend has SSL enabled

### ISSUE THREAD

**Issue by rickatnight11** [sensu/sensu-puppet#1023]
## Description of problem

Puppet run fails on `sensu_api_validator` Exec when Backend has SSL enabled (`cert-file` and `key-file` specified in `backend.yml`, as it always assumes HTTP.  The underlying code actually has a `use_ssl` parameter, but the incantation in `sensu::backend` doesn't currently set it.

## Command used and debugging output

```
$ puppet agent -t
Info: Using configured environment 'production'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Retrieving locales
Info: Loading facts
Info: Caching catalog for mgmt01.example.org
Info: Applying configuration version '1545709040'
Notice: /Stage[main]/Sensu::Backend/Service[sensu-backend]/ensure: ensure changed 'stopped' to 'running'
Info: /Stage[main]/Sensu::Backend/Service[sensu-backend]: Unscheduling refresh on Service[sensu-backend]
Notice: Unable to connect to sensu_api server (http://0.0.0.0:7001): Failed to open TCP connection to 0.0.0.0:7001 (Connection refused - connect(2) for "0.0.0.0" port 7001)
Notice: Failed to connect to sensu_api; sleeping 2 seconds before retry
Notice: Unable to connect to sensu_api server (http://0.0.0.0:7001): wrong status line: "\x15\x03\x01\x00\x02\x02"
Notice: Failed to connect to sensu_api; sleeping 2 seconds before retry
Notice: Unable to connect to sensu_api server (http://0.0.0.0:7001): wrong status line: "\x15\x03\x01\x00\x02\x02"
Notice: Failed to connect to sensu_api; sleeping 2 seconds before retry
Notice: Unable to connect to sensu_api server (http://0.0.0.0:7001): wrong status line: "\x15\x03\x01\x00\x02\x02"
Notice: Failed to connect to sensu_api; sleeping 2 seconds before retry
...
```

## Platform and version information

- Your OS: CentOS 7.5
- Your version of Puppet: OS Puppet 6.1.0
- Your version of Sensu: Sensu-Go 5.1.0
- Your version of this module: `sensu2` (https://github.com/sensu/sensu-puppet/commit/fa0dfd176075925c4f9fc1f7d9c5e2c86d3b38de)

**Comment by treydock** [comment]
@rickatnight11 Would it be possible to share your Puppet definition for `sensu::backend`?  I would like to add some SSL acceptance tests to verify SSL works with the types and our execution of `sensuctl` but am having some issues properly configuring the backend I think, or maybe because I'm using self-signed certificates.

**Comment by rickatnight11** [comment]
@treydock, certainly:

```
sensu::backend::config_hash:
  agent-host: '0.0.0.0'
  agent-port: 7002
  api-listen-address: '0.0.0.0:7000'
  use_ssl: true
  cert-file: '/etc/sensu/ssl/sensu-backend.pem'
  key-file: '/etc/sensu/ssl/sensu-backend.key'
  trusted-ca-file: '/etc/ipa/ca.crt'
  dashboard-host: '0.0.0.0'
  dashboard-port: 7001
  log-level: info
```

I'm using the new `use_ssl` parameter my linked PR adds (happy to handle this a different way, though).  The `cert-file` / `key-file` params are pointing at files provided by my IPA service:

```
$ ipa-getcert list -i 20181203002626
Number of certificates and requests being tracked: 10.
Request ID '20181203002626':
        status: MONITORING
        stuck: no
        key pair storage: type=FILE,location='/etc/sensu/ssl/sensu-backend.key'
        certificate: type=FILE,location='/etc/sensu/ssl/sensu-backend.pem'
        CA: IPA
        issuer: CN=Certificate Authority,O=EXAMPLE.ORG
        subject: CN=mgmt01.example.org,O=EXAMPLE.ORG
        expires: 2020-12-03 00:26:28 UTC
        dns: mgmt01.example.org
        principal name: sensu-backend/mgmt01.example.org@EXAMPLE.ORG
        key usage: digitalSignature,nonRepudiation,keyEncipherment,dataEncipherment
        eku: id-kp-serverAuth,id-kp-clientAuth
        pre-save command: 
        post-save command: 
        track: yes
        auto-renew: yes
```

...and `trusted-ca-file` is pointed at that same IPA service's CA cert.  I've also added that CA cert to the system trust store across all my CentOS 7.5 systems (copied cert to `/etc/pki/ca-trust/source/anchors/` and ran `update-ca-trust`), which I believe is what allowed my `sensuctl` and Sensu Agents trust the Backend.

I'm not sure how to get trust established if using a self-signed cert.  You could totally create your own temporary CA cert, import it into your system trust-stores, like I did above, then sign a cert with it for your backend to use.

**Comment by treydock** [comment]
@rickatnight11 Thanks.  I'm assuming you ran `sensuctl configure` to ensure it was using SSL?

**Comment by rickatnight11** [comment]
Yep! My `api-url` in `~/.config/sensu/sensuctl/cluster` is set to `https://mgmt01.example.org:7000`.

**Comment by treydock** [comment]
Good to know.  I opened #1025 that documents the issue with current handling of `sensuctl configure`.  Ideally one wouldn't have to manually re-run `sensuctl configure` and given the way its state is stored it should be possible to make a type/provider around `sensuctl configure`.

**Comment by ghoneycutt** [comment]
Is this still an issue using the latest version with the merged SSL code you two worked on?

**Comment by rickatnight11** [comment]
This is now working for me using the latest code on the `sensu2` branch.  @treydock extended my original PR with https://github.com/sensu/sensu-puppet/pull/1027.
