### ISSUE TITLE
Illegal method definition of method 'validate_keys' on line 8' in legacy function.

### ISSUE THREAD

**Issue by kscherer** [sensu/sensu-puppet#1055]
## Description of problem

After upgrade of puppetserver to 6.2.0, I started getting to following errors:

     Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Internal Server Error: org.jruby.exceptions.SecurityError: (SecurityError) Illegal method definition of method 'validate_keys' on line 8' in legacy function. See https://puppet.com/docs/puppet/latest/functions_refactor_legacy.html for more information

This was explicitly called out in the 6.2.0 Release Notes:
https://tickets.puppetlabs.com/browse/PUP-9294

The only use of validate_keys in my puppet code is in the puppet-sensu module sensu_sorted_json.rb and I was able to confirm the error was due to the puppet-sensu module by using a test environment without the sensu module which compiled successfully.

I have worked around this by adding "func3x_check = false" to the master section of puppet.conf.

I will see if I can figure out how to refactor sensu_sorted_json.rb  later

## Platform and version information

- Your OS: Ubuntu 16.04
- Your version of Puppet: 6.2.0
- Your version of this module: v2.42.0 (sensu_sorted_json.rb file hasn't changed much since then)

**Comment by treydock** [comment]
It looks like the `sensu_sorted_json` would need to be converted to new function format introduced in Puppet 4.  My read of PUP-9294 is that any legacy function that defines Ruby functions will generate an error so only way to refactor would be to move away from the legacy function and use new function format.

**Comment by treydock** [comment]
@kscherer Can you please try #1056 and see if that resolved your issue without the workaround of using `func3x_check = false`?

**Comment by kscherer** [comment]
Many thanks for the quick response and fix! I was able to integrate the fix and verify that it resolved the errors I was seeing.
