### ISSUE TITLE
Support sensu-go enterprise features

### ISSUE THREAD

**Issue by treydock** [sensu/sensu-puppet#1064]
The documentation for sensu-go 5.2 outlines two enterprise features that need to be supported.

- [x] License
- [x]  Auth

The auth commands require the license be added first which can be handled with autorequires.

**Comment by ghoneycutt** [comment]
@treydock Do we have a PR for Auth? Seems #1066 was for License.

**Comment by treydock** [comment]
#1066 also had auth:

https://github.com/sensu/sensu-puppet/blob/sensu2/lib/puppet/type/sensu_ldap_auth.rb

**Comment by ghoneycutt** [comment]
It mentioned that it only partially closed this issue. If we're all good, close this.

**Comment by treydock** [comment]
Ya initial commit was just license file but later commits added auth.  Closing.
