### ISSUE TITLE
Sensu2: allow using internal repo work

### ISSUE THREAD

**Issue by maxadamo** [sensu/sensu-puppet#1069]
## Description of problem

- I have set on hiera `sensu::manag_repo: false`
- The module fails to intsall, because it has `require` set against `sensu::repo`
- skip the code inside `sensu::repo` if false is set

## Command used and debugging output

- What does your puppet config look like (including any hiera config)
- Is this a masterless or master based puppet setup?

## Platform and version information

- Your OS: CentOS / Ubuntu
- Your Ruby version: this is Sensu-Go
- Your version of Puppet: 6.2
- Your version of Sensu: 5.2
- Your version of this module: sensu2 branch, pulling the latest updates

## Anything else to add that you think will be helpful?

please checl this proposed solution: PR #1068

**Comment by ghoneycutt** [comment]
Closed by https://github.com/sensu/sensu-puppet/pull/1070
