### ISSUE TITLE
puppetlabs-apt version 6.3.0 compatibility (instead of current 4.1.0)

### ISSUE THREAD

**Issue by osehgol** [sensu/sensu-puppet#1090]
## Description of problem

- What did you do?

_puppet agent -t_ 

- What happened?

_Error: Found 1 dependency cycle:
(Exec[apt-update] => Package[apt-transport-https] => Apt::Source[sensu] => Exec[apt-update])\nCycle graph written to /opt/puppetlabs/puppet/cache/state/graphs/cycles.dot.
Error: Failed to apply catalog: One or more resource dependency cycles detected in graph_

- What did you expect to happen?

**successfully compiled catalog without dependency issues**

- How can someone reproduce the problem?

**use puppetlabs-apt module version 6.3.0 alongside sensu**

## Command used and debugging output

- What does your puppet config look like (including any hiera config)
- Is this a masterless or master based puppet setup?
**master based**

## Platform and version information

- Your OS: **Ubuntu 16.04**
- Your Ruby version: **2.3.1p112**
- Your version of Puppet: **5.5**
- Your version of Sensu: **2.63**
- Your version of this module: 

## Anything else to add that you think will be helpful?
**this problem does not occur when using puppetlabs-apt 4.1.0. please update sensu to be compatible with puppetlabs-apt 6.3.0 **

**Comment by ghoneycutt** [comment]
Thanks for reporting this! Would you like to try a fix? You can update the `.fixtures.yml` and `metadata.json` to change the value for the apt module version and the tests will automatically run and see if it works.

**Comment by treydock** [comment]
If only increasing the upper bound , update `.fixtures-latest.yml`.  If we update lower bound then it's `.fixtures.yml`.
