### ISSUE TITLE
Different namespace for the sensu-go version

### ISSUE THREAD

**Issue by derkgort** [sensu/sensu-puppet#1092]
Hi,

Would it be an idea to use a different namespace for the sensu-go version of this module? Right now it's not possible to have both the sensu1 and and sensu-go versions of this puppet module active in the same puppet environment. And that makes switching from sensu1 not easy to do.

So maybe keep using sensu for 1 and use sensugo for sensu go/5.

**Comment by ghoneycutt** [comment]
We are currently transitioning the master branch of this repo which configures sensu v1 to a new module named sensuclassic. We will update this issue when that is ready.

https://github.com/sensu/puppet-module-sensuclassic

**Comment by derkgort** [comment]
Ah great! That works too. Thanks.

**Comment by ghoneycutt** [comment]
sensuclassic is now available!

https://forge.puppet.com/sensu/sensuclassic
