### ISSUE TITLE
Backward incompatibility change with SSL handling

### ISSUE THREAD

**Issue by cjeanner** [sensu/sensu-puppet#1098]
Dear Sensu team,
One of the [latest changes](https://github.com/sensu/sensu-puppet/commit/c907aa3727fe1514074bb40dbbaa3c9a743e3298) in the code base of this module apparently broke existing deploys in a specific case: when no puppet-server is involved.

In such a case, there isn't any puppet CA, thus the variable $facts['puppet_localcacert'] is set to Undef, and this "value" is refused by the String type.

Would it be possible to make some more checks on that value, and:
- allow Undef (Variant[Undef, String] $ssl_ca_source - same goes for the other new ssl related variables)
- ensure it's NOT undef when you include the ::sensu::ssl class

That would be really helpful!

Cheers,
C.

**Comment by treydock** [comment]
@cjeanner Give #1100 a try and let us know if that solves your problem. I made all the ssl source parameters optional which handles the `Undef` case.  I also made is so an error will be raised if those parameters are undefined and SSL is still enabled.

**Comment by ghoneycutt** [comment]
Please re-open if you are still having an issue after using the changes that were just merged.
