### ISSUE TITLE
Community plugins are not available for Debian

### ISSUE THREAD

**Issue by Debilski** [sensu/sensu-puppet#1099]
`class sensu::repo::community` adds packages at `"https://packagecloud.io/sensu/community/${downcase($facts['os']['name'])}/"` but then fails on Debian because there are not packages available under `https://packagecloud.io/sensu/community/debian`. (https://packagecloud.io/sensu/community)

**Comment by jaredledvina** [comment]
I think this is a duplicate of the existing upstream issue https://github.com/sensu/sensu-plugins-omnibus/issues/3

**Comment by Debilski** [comment]
Thanks. I see that ansible has a flag to manage the community repo oneself. Does this exist for puppet also?

**Comment by treydock** [comment]
You can pass `manage_repo => false` to the `sensu` class to disable management of the repo.

**Comment by treydock** [comment]
@Debilski Did setting `manage_repo => false` solve the issue?  If you need debian community repo you may want to comment on https://github.com/sensu/sensu-plugins-omnibus/issues/3 to let them know this issue is affecting more people.

**Comment by Debilski** [comment]
Yeah, works good enough for me. Thanks. For the plugins I was interested in, I could just use the Ubuntu versions.
