### ISSUE TITLE
Could not autoload

### ISSUE THREAD

**Issue by maximnik** [sensu/sensu-puppet#1102]
## Description of problem

- What did you do?
I've downloaded modul sensu and trying to install backend. Module was added to environment production on puppet server.

- What happened?
While run puppet, I get error:
```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Type-Name, Could not autoload puppet/type/sensu_configure: Could not autoload puppet/provider/sensu_configure/sensuctl: /etc/puppetlabs/code/environments/production/modules/sensu/lib/puppet/provider/sensuctl.rb:84: syntax error, unexpected tLABEL
  def self.sensuctl_set(command, name, property, value: nil, flags:  nil)
                                                       ^ at /etc/puppetlabs/code/environments/production/modules/sensu/manifests/backend/tessen.pp:19:7
```

I've tried to restart puppetserver, but error stay the same.

- What did you expect to happen?
Expect sensu backend to be installed and configured.

## Command used and debugging output

- What does your puppet config look like (including any hiera config)
Configuration in puppet:
`class { 'sensu::backend': }`

- Is this a masterless or master based puppet setup?
```
Puppetserver: puppetserver-2.8.1-1.el6
Puppet agent: puppet-agent-1.10.14-1.el6
```

## Platform and version information

- Your OS: Amazon Linux 
- Your Ruby version:
- Your version of Puppet: puppetserver-2.8.1-1.el6
- Your version of this module: master

**Comment by ghoneycutt** [comment]
You are using Puppet 4 which is not compatible with this module. You need Puppet 5 at the minimum. You could upgrade Puppet or use the Sensu Classic code base with Puppet 4 using this module https://github.com/sensu/puppet-module-sensuclassic

**Comment by derkgort** [comment]
Hi,

I'm not using puppet 4. I'm using puppet 5 and I also run into this issue:

puppet-agent-5.5.8
puppetserver-5.3.6

Or am I missing something?

Changing sensu/lib/puppet/provider/sensuctl.rb:102
from
def self.sensuctl_set(command, name, property, value: nil, flags:  nil)
to
def self.sensuctl_set(command, name, property, value, flags)

will fix it.

**Comment by treydock** [comment]
@derkgort I should be able to change this and maintain backwards compatibility with previous behavior. I had forgotten Puppetserver 5.x uses JRuby 1.9.3 which I think is old enough to not support this newer syntax.  Our tests all run with `puppet apply` which uses the newer ruby bundled with `puppet-agent`.
