### ISSUE TITLE
Add support for Hiera 5 "deep merge" equivalent.

### ISSUE THREAD

**Issue by madelaney** [sensu/sensu-puppet#1104]
## Description of problem

- What did you do?

Using Hiera v5, I'm trying to pull in Hiera data from multiple sources within my hiera lookup path.

- What happened?

Only the first value in the Hiera lookup path was used.

- What did you expect to happen?

I'd like to have all applicable Hiera values evaluated as a "deep merge" of data.

- How can someone reproduce the problem?

Using the {{sensu-go}} sandbox, split the hiera data into hunks (vs. the current setup of being single sourced).

## Command used and debugging output

- What does your puppet config look like (including any hiera config)

```YAML
{
  'name' => 'per-node data',
  'path' => 'node/%{trusted.certname}.yaml'
},
{
  'name'  => 'per-os defaults',
  'paths' => [
    'osfamily/%{facts.os.name}/%{facts.os.release.major}.yaml',
    'osfamily/%{facts.os.family}/defaults.yaml'
  ]
},
{
  'name' =>  'Global yaml file',
  'path' =>  'common.yaml'
}
```

- Is this a masterless or master based puppet setup?

Master based puppet setup.

## Platform and version information

- Your OS: Ubuntu 16.04LTS (amd64)
- Your Ruby version: ruby 2.3.1p112
- Your version of Puppet: Puppet OSS 4.10.12
- Your version of Sensu: sensu-go 5.5
- Your version of this module: 3.1.0

**Comment by madelaney** [comment]
In this case, I believe the "fix" would be to use the [hiera deep](https://puppet.com/docs/puppet/5.0/hiera_merging.html#deep) function

**Comment by treydock** [comment]
@madelaney Try using `lookup_options` in your Hiera code: https://puppet.com/docs/puppet/5.0/hiera_merging.html#lookupoptions-format

Something like this:

```yaml
lookup_options:
  sensu::backend::checks:
    merge: deep
```

**Comment by ghoneycutt** [comment]
@madelaney This should go in your `common.yaml`.

**Comment by madelaney** [comment]
@ghoneycutt Are you saying the `lookup_options` should go in `common.yaml`?

**Comment by ghoneycutt** [comment]
yes, the code that @treydock demonstrated should go in your `common.yaml`

**Comment by madelaney** [comment]
@ghoneycutt Awesome, thanks.
