### ISSUE TITLE
Sensu Go: password change when using a backend cluster causes sensuctl failures.

### ISSUE THREAD

**Issue by rgeniesse** [sensu/sensu-puppet#1118]
## Description of problem

- What did you do?
Attempted to change the default password of the Sensu Go admin user with Puppet code.
- What happened?
One cluster member was able to make the password change, but when the other 2 went to change it, it failed, as the password was already changed by the "first" member and the configured old password was no longer valid.
- What did you expect to happen?
The password to change and all puppet runs on each cluster member do not time out.
- How can someone reproduce the problem?
Create a 3 node sensu backend cluster and apply the following code:
```
class { 'sensu::backend':
  agent_password     => 'supersecret',
  agent_old_password => 'P@ssw0rd!',
}
```

One member will win at changing the password, while the other two will not.

## Command used and debugging output

- What does your puppet config look like (including any hiera config)
```
class { 'sensu::backend':
  agent_password     => 'supersecret',
  agent_old_password => 'P@ssw0rd!',
}
```

Should be enough to reproduce it once applied to a 3 node cluster. You'll also need the code required to build the actual cluster, which is provided as Hiera code in the Readme.
- Is this a masterless or master based puppet setup?
Master based.

## Platform and version information

- Your OS: 
- Your Ruby version:
- Your version of Puppet: 
- Your version of Sensu: 5.9.
- Your version of this module: 3.3.0

## Anything else to add that you think will be helpful?

Should be straightforward to setup and reproduce. Let me know if it is not and I'll see if I can locally.

**Comment by treydock** [comment]
@rgeniesse Was it the case that the catalog for all 3 was applied at the same time or were they staggered?  If they were all applied at the same time and they all thought they had password needing updates at same time it would make sense you saw this error as the state is shared between cluster members so if one changed password and others aren't aware of that change then things will break. It could be the case that we need to document staggering Puppet runs between clustered backends.

Do subsequent puppet runs succeed or do some cluster members have errors even after the password is changed?

**Comment by ghoneycutt** [comment]
Do we need to declare the password on multiple backends or is the fix to just declare things on one backend and let it propagate the configs?

**Comment by treydock** [comment]
I am fairly certain that objects like the agent user can be modified on one and it will be modified for all but we manage agent password by default so in that case you'd have to make sure the password is set on all 3 backends but gets applied to one and the other 2 should require no changes once the first applies the change.  Like if backend1 made the change then subsequent runs of backend2 and backend3 should require no change to the agent password as long as the values passed in match on all 3 systems.

**Comment by treydock** [comment]
For something like agent password if they don't all match in Puppet configs then one would be constantly changing the value set by another so they have to match.

**Comment by treydock** [comment]
I tested with Vagrant and had no issues when I applied agent password on one backend and then ran Puppet on second backend after first ran Puppet. Both backends had updated agent password but only one of them had to apply the change using Puppet.

**Comment by rgeniesse** [comment]
@treydock thanks for testing. It would seem then that there was something specific to the user's environment or possible the feature was being used incorrectly. I don't have direct access to that code anymore. I'll go ahead and close this out since given your test, it seems like I'd find the same conclusion as what you did is what I was going to do. Thanks for looking into it and sorry for the non-issue.
