### ISSUE TITLE
Duplicate Resource Declaration When Trying to use Custom SSL Settings

### ISSUE THREAD

**Issue by csoleimani** [sensu/sensu-puppet#1127]
## Description of problem

- What did you do?

**When trying to use custom SSL settings, I get a duplicate resource declaration**

- What happened?

**Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Resource Statement, Duplicate declaration: Class[Sensu] is already declared; cannot redeclare (file: /etc/puppetlabs/code/environments/staging/site/profile/manifests/sensugo/server/main.pp, line: 60) (file: /etc/puppetlabs/code/environments/staging/site/profile/manifests/sensugo/server/main.pp, line: 60, column: 3)**

- What did you expect to happen?

Sensu::Backend/Sensu_configure[puppet]/trusted_ca_file should allow changes

- How can someone reproduce the problem?

Call the sensu::backend class and sensu class like in the example

- What does your puppet config look like (including any hiera config)

```
  class {
    '::profile::nginx::non_saml':
      fqdn             => $api_fqdn,
      proxy            => 'https://sensugo',
      upstream_members => [ '127.0.0.1:3000' ],
    ;
    'sensu':
      ssl_ca_source => '/etc/ssl/company/trust/puppetmasterca.pem'
    ;
    'sensu::backend':
      license_source  => 'puppet:///modules/profile/sensu/go/license.json',
      config_hash     => $config,
      url_host        => "${facts['location']}-${api_fqdn}",
      ssl_cert_source => 'puppet:///modules/profile/sensu/go/sensugo-staging.corp.company.internal.crt',
      ssl_key_source  => 'puppet:///modules/profile/sensu/go/sensugo-staging.corp.company.internal.key',
    ;
  }
```

- Is this a masterless or master based puppet setup?

Master

## Platform and version information

- Your OS: Debian 9
- Your Ruby version:
- Your version of Puppet: Enterprise 2019
- Your version of Sensu: 5.11.1#39d2bf2
- Your version of this module: 87d4deab7b0282d8c286956e72dedb09ee141fe1

## Anything else to add that you think will be helpful?

It looks to me like backend.pp simply [includes sensu](https://github.com/sensu/sensu-puppet/blob/f55a44ac7e1f35928c0a0401f857192e1285df89/manifests/backend.pp#L148) instead of calling it with a class where you can modify the parameters, and has an unchangeable $trusted_ca_file variable

**Comment by treydock** [comment]
If we called `sensu` class using `class { 'sensu': }` in the module then your example would most definitely cause duplicate declaration.  If you call `class { 'sensu': }` then later do `include sensu` that's fine, because include won't cause duplicate resource. Also because a host can have both agent and backend we can't use class declaration using `class { 'sensu': }` as that would break if you had both agent and backend classes which both need that class.

I would try splitting your class declaration into 2 separate statements and see if that helps because we do this in our acceptance tests:

```puppet
class { 'sensu':
      ssl_ca_source => '/etc/ssl/company/trust/puppetmasterca.pem'
    }
class { 'sensu::backend':
      license_source  => 'puppet:///modules/profile/sensu/go/license.json',
      config_hash     => $config,
      url_host        => "${facts['location']}-${api_fqdn}",
      ssl_cert_source => 'puppet:///modules/profile/sensu/go/sensugo-staging.corp.company.internal.crt',
      ssl_key_source  => 'puppet:///modules/profile/sensu/go/sensugo-staging.corp.company.internal.key',
  }
```
The subject of issue made it sound like this is somehow related to your SSL settings. We don't treat classes differently for SSL settings. Did you observe different behavior when you remove custom ssl settings?

**Comment by csoleimani** [comment]
I tried this previously, and have the same duplicate resource declaration:

```
  class {'sensu':
    ssl_ca_source => '/etc/ssl/company/trust/puppetmasterca.pem'
  }

  class {
    '::profile::nginx::non_saml':
      fqdn             => $api_fqdn,
      proxy            => 'https://sensugo',
      upstream_members => [ '127.0.0.1:3000' ],
    ;
    'sensu::backend':
      license_source  => 'puppet:///modules/profile/sensu/go/license.json',
      config_hash     => $config,
      url_host        => "https://${facts['location']}-${api_fqdn}:8080",
      ssl_cert_source => 'puppet:///modules/profile/sensu/go/sensugo-staging.corp.company.internal.crt',
      ssl_key_source  => 'puppet:///modules/profile/sensu/go/sensugo-staging.corp.company.internal.key',
    ;
  }
```

If I go back to how things were before trying to use custom ssl settings like this:

```
class { 'sensu::backend':
      license_source  => 'puppet:///modules/profile/sensu/go/license.json',
      config_hash     => $config,
      url_host        => "${facts['location']}-${api_fqdn}",
  }
```


puppet is fine without failures, but then I'm unable to use a different certificate authority

**Comment by csoleimani** [comment]
For whatever reason, if I move the class {'sensu':} declaration to the manifest that has the sensu::agent resource declaration from the server manifest that had the sensu::backend declaration, the duplicate resource error goes away. Sorry for the false alarm
