### ISSUE TITLE
Feature request: Add ability to have configuration changes reload sensu-enterprise instead issuing a restart

### ISSUE THREAD

**Issue by rgeniesse** [sensu/sensu-puppet#1130]
## Description of feature request

In Sensu Enterprise 2.6.0, a `reload` option was added to interactive with the service `sensu-enterprise`:

https://docs.sensu.io/sensu-enterprise/3.6/changelog/#enterprise-v2-6-0

> IMPROVEMENT: Sensu Enterprise now loads configuration and validates it prior to reloading (SIGHUP). If configuration is determined to be invalid prior to reloading, Sensu will report invalid configuration definitions, and it will continue to run with its existing working configuration.

Currently, when a configuration change is detected in `/etc/sensu/conf.d/` and Sensu Enterprise is being used, Puppet will attempt a `restart` on the `senssu-enterprise` service. If invalid JSON some how ends up inside `/etc/sensu/conf.d/`, this will cause the service to be stopped and then started again, putting `sensu-enterprise` into a non-running state.

This request is to have an option added for Puppet to execute a `reload` against `sensu-enterprise` instead of a `restart` on configuration changes, which allows for the above linked and quoted feature of the `sensu-enterperirse` service to be taken advantage of.

In looking at the code, a `notify` is being done to the service for configuration changes in `/etc/sensu/conf.d`, which based on Puppet documentation, results in a `restart` of the service.

https://github.com/sensu/sensu-puppet/blob/v2.63.0/manifests/check.pp#L271
https://github.com/sensu/sensu-puppet/blob/v2.63.0/manifests/write_json.pp#L60
https://puppet.com/docs/puppet/5.3/metaparameter.html#notify

**Comment by csoleimani** [comment]
This repository is for sensu go now. You probably want to open this issue under here:

https://github.com/sensu/puppet-module-sensuclassic

**Comment by rgeniesse** [comment]
Ah, didn't realize that existed. Thanks @csoleimani!
