### ISSUE TITLE
Unable to Create sensu_role_binding that maps to a ClusterRole

### ISSUE THREAD

**Issue by csoleimani** [sensu/sensu-puppet#1131]
- What did you do?
**Create a role binding, and referenced a cluster-role in the 'role_ref' parameter**
- What happened?
**The role_binding always assumes the type is Role,**
- What did you expect to happen?
**I want to either be able to specify role or cluster role.**
- How can someone reproduce the problem?
**use a sensu_role_binding resource type, and put a cluster role in the role_ref parameter**

- What does your puppet config look like (including any hiera config)

```
    sensu_role_binding { $team:
      role_ref  => 'edit_no_handlers',
      subjects  => {
        'type' => 'Group',
        'name' => "ad:${team}",
      },
      namespace => $team,
    }
```

I also tried turning role_ref into a hash with a 'name' and 'type' param like below, but puppet errors:

```
  sensu_role_binding { $team:
   role_ref  => {
        'name' => 'edit_no_handlers',
        'type' => 'ClusterRole'
      },
      subjects  => {
        'type' => 'Group',
        'name' => "ad:${team}",
      },
```
This is the error I'd get:

**Error: /Stage[main]/Profile::Sensugo::Server::Rbac/Sensu_role_binding[ts-corpsys]: Could not evaluate: sensuctl create ts-corpsys failed
Error message: Execution of '/usr/bin/sensuctl create --file /tmp/sensuctl20190815-12612-1gyy33s' returned 1: resource 0: (offset 57): json: cannot unmarshal object into Go struct field RoleRef.name of type string
Error: some resources couldn't be parsed**

- Is this a masterless or master based puppet setup?
Master
## Platform and version information

- Your OS: Debian 9
- Your Ruby version: 2.3.3
- Your version of Puppet:6.4.3
- Your version of Sensu: 5.11.1-5015
- Your version of this module: 978f6e2c6ce05d5d4e6b409e10678bebe14342c2 (namespaces branch)

**Comment by treydock** [comment]
@csoleimani 

Your first example should work but I found the problem.  You need to ensure the `namespace` for `$team` exists. Notice in the error below the `PUT` has the namespace in URL which has to exist.  The types that use namespaces will auto-require the namespace if it's defined in Puppet.

BEFORE creating a namespace for `$team`:
```
Error: sensuctl create devs failed
Error message: Execution of '/bin/sensuctl create --file /tmp/sensuctl20190817-4321-1sb2u8m' returned 1: Error: error putting resource 0 (/api/core/v2/namespaces/devs/rolebindings/devs): PUT "/api/core/v2/namespaces/devs/rolebindings/devs": Put https://sensu-backend.example.com:8080/api/core/v2/namespaces/devs/rolebindings/devs: EOF
Error: /Stage[main]/Main/Sensu_role_binding[devs]/ensure: change from 'absent' to 'present' failed: sensuctl create devs failed
Error message: Execution of '/bin/sensuctl create --file /tmp/sensuctl20190817-4321-1sb2u8m' returned 1: Error: error putting resource 0 (/api/core/v2/namespaces/devs/rolebindings/devs): PUT "/api/core/v2/namespaces/devs/rolebindings/devs": Put https://sensu-backend.example.com:8080/api/core/v2/namespaces/devs/rolebindings/devs: EOF
```

AFTER creating namespace:
```
Notice: /Stage[main]/Main/Sensu_role_binding[devs]/ensure: created
```

Could just do this:
```
sensu_namespace { $team: ensure => 'present' }
```

For your second example, I think what you're looking for is `sensu_cluster_role_binding` type.  `role_ref` is only the `name` portion of specification from Sensu Go. We should probably validate the property better since it doesn't directly map to Sensu Go resource specification because cluster roles and regular roles and bindings had to be treated differently.

```puppet
sensu_cluster_role_binding { $team:
   role_ref  =>  'edit_no_handlers'
   subjects  => {
        'type' => 'Group',
        'name' => "ad:${team}",
    },
}
```

The above would generate this JSON part for `role_ref`:

```
"role_ref": { "name": "edit_no_handlers", "type": "ClusterRole" }
```

The `type` part is hardcoded into the provider.

**Comment by csoleimani** [comment]
Hi, Trey. Thanks for responding so fast.

We're have already ensured that all the namespaces are present, but I suppose it wouldn't hurt to do a `require => Sensu_namespace[$team]`. The namespaces not existing is not the problem I'm having. Here is why I do not want to use a cluster-role:

Let's say we have these three namespaces: linux, windows, default. 

for simplicity's sake, there's an ad group with the same exact name that we map to.

I want the linux team to have full admin access, except to handlers because there are secrets in the handlers in the linux and default namespaces. However, I want them to have read-only access in the windows namespace.

If I use the sensu_cluster_role_binding type and reference 'edit_no_handlers,'  then the linux team will have 'edit_no_handlers' across all namespaces, which gives them too much access to the windows namespace.

Looking at the documentation, it says this:

Role bindings and cluster role bindings

A role binding assigns a role or cluster role to users and groups within a namesapce. A cluster role binding assigns a cluster role to users and groups across namespaces and resource types.


So I'm hoping the type for role_biding could be changed to have the flexibility to map to either a ClusterRole, or regular Role, instead of assume regular Role. Does that make more sense? Sorry if I am not explaining it that well

**Comment by csoleimani** [comment]
For what it's worth, I was able to write a bash script to iterate trough the namespaces and role-bindings, and use a sed to replace the type to ClusterRole, so I'm not entirely blocked, but I think being able to specify which type between Role or ClusterRole would be nice, since role bindings let you choose one or the other

**Comment by treydock** [comment]
I misunderstood of the specification for the two types of role bindings. I thought that a role binding could only have a `role_ref` with `type` of `Role` and cluster role bindings of `type` that is `ClusterRole`. I just verified that I'm able to create a `RoleBinding` with `role_ref` of `type` that is `ClusterRole`.

**Comment by csoleimani** [comment]
Hmm, could you share what that puppet code looks like?
