### ISSUE TITLE
allow to remove the prefix "^sensu-(plugins|extensions)" from sensu::plugins

### ISSUE THREAD

**Issue by maxadamo** [sensu/sensu-puppet#1155]
## Description of problem

- What did you do? 

I installed `sensu-plugins-memory-checks`
one of the scripts contained in the plugin is called: `check-ram.rb`
`check-ram.rb` requires a gem called `vmstat`
You can check the documentation on Bonsai: [sensu-plugins-memory-checks](https://bonsai.sensu.io/assets/sensu-plugins/sensu-plugins-memory-checks)

- What happened? 

I tried to install the gem `vmstat` using `sensu::plugins` but it fails because it prepends the prefix and it's not possible to customize this prefix. 

- What did you expect to happen? 

I'd like to have a parameter called, for instance, `prefix`, which defaults to  `^sensu-(plugins|extensions)` but, for instance, it can be set to null: 
`prefix => '',`

**Comment by treydock** [comment]
@maxadamo I added #1156 that would allow you to install gems into Sensu's embedded Ruby. Adding a `prefix` property to the `sensu_plugin` type would be difficult as there are two types of prefixes and the property `extension` already modifies the prefix of the gem that gets installed.

**Comment by treydock** [comment]
Usage would either be:

```puppet
package { 'vmstat':
  ensure   => 'installed',
  provider => 'sensu_gem',
}
```

Or

```puppet
class { 'sensu::plugins':
  gem_dependencies => ['vmstat'],
}
```

**Comment by maxadamo** [comment]
I didn't comment yet, but that's of course better (it is the same as the old sensu if I recall correctly). 
Thanks.
