### ISSUE TITLE
Password changing and running `sensuctl configure` is fragile

### ISSUE THREAD

**Issue by treydock** [sensu/sensu-puppet#1163]
I have run into issues when testing where changing the password and going from SSL to non-SSL at the same time results in errors. The logic for `sensu_configure` to determine which password to use is a bit fragile.

**Comment by treydock** [comment]
This is going to require using only the Sensu API to manage users because if the password is changed when SSL is changed then sensuctl config is removed to fix SSL settings but `sensuctl configure` won't work until the user password is updated and `sensu_user` comes after `sensu configure`. If the `sensu_user` resource uses just the API then it can be run before `sensuctl configure` which would also remove all bootstrap logic added in #1164

**Comment by maxadamo** [comment]
how about changing these into `Sensitive` inside `backend.pp`? 
```
String $password = 'P@ssw0rd!',
String $agent_password = 'P@ssw0rd!',
Optional[String] $agent_old_password = undef,
String $postgresql_password = 'changeme',
```

**Comment by treydock** [comment]
That would be useful but not solve the problem. There is a fix in #1164 . Should be noting that using the API directly didn't help, real fix was just extra provider logic in sensu_configure.

**Comment by maxadamo** [comment]
yep, sorry. I didn't meant to provide a solution, but I just wanted to add another topic.

**Comment by maxadamo** [comment]
my two cents on the Sensitive datatype. In my modules, in order to avoid breaking changes, for one or two release, I use `Variant[String|Sensitive]` and if `string` is being used I emit a warning. After a couple of release I force the usage of `Sensitive`
