### ISSUE TITLE
getting a warning on url, sha512, filters usage, but the documentation lacks necessary information

### ISSUE THREAD

**Issue by maxadamo** [sensu/sensu-puppet#1169]
## Description of problem

- I'm getting a warning but the README doesn't actually say how to circumvent this warning (I didn't dig into the code, and it's still unclear to me how clear up this message). 

`Using url, sha512, filters, or headers properties for single build is deprecated, use builds property`

![warning](https://user-images.githubusercontent.com/1710103/68548378-8b275f80-03ec-11ea-951f-3ada59294456.png)

**Comment by treydock** [comment]
@maxadamo Looks like our Github hosted puppet-strings docs were out of date. I forced an update. http://sensu.github.io/sensu-puppet/puppet_types/sensu_asset.html. We moved `url`, `sha512` and `filters` into the `builds` property to match the preferred approach by Sensu Go.  Can provide one item in the `builds` array if you don't need multiple builds.

**Comment by ghoneycutt** [comment]
We should add a section to the readme with this warning and a before and after with an example of the old code that would create the warning and an example of what the new code should look like.
