### ISSUE TITLE
Support PDK

### ISSUE THREAD

**Issue by treydock** [sensu/sensu-puppet#1182]
This module should support PDK which could help contributors run tests and develop on this module.

**Comment by ghoneycutt** [comment]
Please use ghoneycutt/rpcbind as a guide with regards to rubocop. Rubocop is not stable and they change their style very often which has negative effects for us and others contributing so we want to minimize rubocop changes.

https://github.com/ghoneycutt/puppet-module-rpcbind/blob/master/.sync.yml

**Comment by treydock** [comment]
This works too:

```
 .rubocop.yml:
   selected_profile: off
```

This disable all cops but struggling to disable the use of rubocop-rspec which is having issues parsing files even when cops are disabled.

**Comment by treydock** [comment]
This is what I landed on:

```
.rubocop.yml:
  default_configs:
    AllCops:
      Exclude:
        - '**/*'
```

The `selected_profile` works but couldn't force it to use newer ruby parser and kept using 2.1 and that would break even when cops were disabled.
