### ISSUE TITLE
Add support for 'sensuctl commands'

### ISSUE THREAD

**Issue by treydock** [sensu/sensu-puppet#1187]
This was originally part of #1174 but is delayed due to issues with the documentation for how to interact with Bonsai using `sensuctl commands`. Blocking issues:

<s>sensu/sensu-go#3420</s>
<s>sensu/sensu-go#3421</s>

**Comment by ghoneycutt** [comment]
Sensu-go should have this in their next release. Please keep open so we can track cleanup of our work around.
