### ISSUE TITLE
[Feature Request] - Add possibility to use hiera when adding ssl cert & keys

### ISSUE THREAD

**Issue by tdmike** [sensu/sensu-puppet#1196]
Currently, you can only add SSL certs and keys using the constraints of source. When using GIT as a source for the puppet code this would mean that private keys are uploaded to GIT without any encryption. I would like to see the use of content to allow usage of eYAML through hieradata.

Example:

https://github.com/sensu/sensu-puppet/blob/3a4d35fe5131949ca6be71de2d37071da9e85924/manifests/backend.pp#L215

With the license, you do allow to either use source or content parameter:
https://github.com/sensu/sensu-puppet/blob/3a4d35fe5131949ca6be71de2d37071da9e85924/manifests/backend.pp#L184
https://github.com/sensu/sensu-puppet/blob/3a4d35fe5131949ca6be71de2d37071da9e85924/manifests/backend.pp#L185

Allowing both parameters would allow us to add a private key to the backend in a secure way.

**Comment by ghoneycutt** [comment]
Thank you for reporting this! While we work on modifying the code to better support this, you can work around it by adding those files in your profile code and then changing the sensu parameters to read the files locally. So the source would use `file:///path/to/file`

**Comment by tdmike** [comment]
Hi, I already started working on modifying the code (https://github.com/sensu/sensu-puppet/pull/1197) However I have no proper way to test since I currently don't have a testing environment (I ran into this problem in our production environment)

**Comment by treydock** [comment]
@tdmike I continued your pull request in #1198

**Comment by ghoneycutt** [comment]
@tdmike This new functionality is in v4.2.0. You can check out the new parameter names in the commit at https://github.com/sensu/sensu-puppet/pull/1198/files
