### ISSUE TITLE
[Feature Request] Add ability to remove default agent user and groups

### ISSUE THREAD

**Issue by tdmike** [sensu/sensu-puppet#1205]
## Description of problem
As we are running the Enterprise variant of Sensu, we are setting up TLS Authentication. In the process of setting this up, I removed the agent user and system:agents group as described in the Sensu Docs. However, the next puppet run put it back in. 

I would like to have the ability to disable the configuring of the default user since it's impossible to remove while using puppet.

**Comment by tdmike** [comment]
Could possibly be fixed by adding an if statement based on an overridable variable to the backend.pp

Something like this:
`  if $enable_agent_user {
    sensu_user { 'agent':
      ensure       => 'present',
      disabled     => false,
      password     => $sensu::agent_password,
      old_password => $sensu::agent_old_password,
      groups       => ['system:agents'],
    }
  }`

**Comment by treydock** [comment]
I think something like `$manage_agent_user` would be appropriate.

For now you could add something like this to a profile class:

```puppet
Sensu_user <| title == 'agent' |> {
  ensure => 'absent'
}
```

I haven't tested this but that kind of pattern is common to modify already defined resources.

**Comment by tdmike** [comment]
Thanks, I will try that out as a work around, should I create the pull request with your suggested variable?

**Comment by treydock** [comment]
You can open a pull request if you'd like. Just be sure it includes rspec tests to cover the new behavior. If you'd prefer I can make the change this evening.

That's right, I think at least with `sensuctl` it's not possible to delete a user. I don't recall if the `sensu_api` provider is a way to bypass this but because of the condition in `sensu_user` type you'll be unable to set `ensure => 'absent'`. I'll experiment later today to see if deleting users in Sensu Go is still not supported.

**Comment by tdmike** [comment]
From what I know in `sensuctl` is that it's only possible to deactivate a user. Which could be a viable option but should be clearly specified then. 

I would like to add the pull request but I'm not familiar enough with rspec.

**Comment by ghoneycutt** [comment]
@tdmike Could you please test the code in PR #1206 and let us know how it goes?

**Comment by tdmike** [comment]
@ghoneycutt Just tested it in our development environment, everything works as expected. One thing I did ran into is the following:
```
Notice: /Stage[main]/Sensu::Backend/Sensu_user[agent]/password: changed password
Notice: /Stage[main]/Sensu::Backend/Sensu_user[agent]/disabled: disabled changed 'true' to 'false'
Error: /Stage[main]/Sensu::Backend/Sensu_user[agent]: Could not evaluate: old_password given for agent is incorrect
Notice: /Stage[main]/Sensu::Backend::Default_resources/Sensu_cluster_role_binding[system:agent]: Dependency Sensu_user[agent] has failures: true
Warning: /Stage[main]/Sensu::Backend::Default_resources/Sensu_cluster_role_binding[system:agent]: Skipping because of failed dependencies
```
When the user is disabled and I set manage_agent_user to true it gives this error. Which is logical since it tries to evaluate the password on a disabled user. However you can't do anything with a disabled user.

**Comment by treydock** [comment]
This maybe a bug in `sensu_user`. I'll try to reproduce and see where the problem lies.

**Comment by tdmike** [comment]
From what I can gather the password change is executed before enabling or disabling the user.

**Comment by treydock** [comment]
I found a bug with `sensu_user` that would cause it to try and change the password of disabled users. I updated the logic to correctly not manage passwords for disabled sensu users.

**Comment by treydock** [comment]
Try #1206 again, there is a new commit that fixes the bug.

**Comment by tdmike** [comment]
That fixed it 👍

**Comment by ghoneycutt** [comment]
@tdmike Thanks for all the help! This is in v4.4.0
