### ISSUE TITLE
Error 500 on SERVER: Server Error: no parameter named 'configure_trusted_ca_file'

### ISSUE THREAD

**Issue by tdmike** [sensu/sensu-puppet#1209]
## Description of problem

- What did you do?
Update module to 4.4.1
- What happened?
Received an error regarding the `configure_thrusted_ca_file`
- What did you expect to happen?
A successful puppet run
- How can someone reproduce the problem?
I have no clue what went wrong, it's a enterprise configuration that's beeing build up.
## Command used and debugging output
```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: no parameter named 'configure_trusted_ca_file' (file: /etc/puppetlabs/code/environments/its_development/modules/sensu/manifests/backend.pp, line: 195) on Sensu_user[admin] (file: /etc/puppetlabs/code/environments/its_development/modules/sensu/manifests/backend.pp, line: 195) on node example01.example.org
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```
- What does your puppet config look like (including any hiera config)

- Is this a masterless or master based puppet setup?
This is master based puppet setup
## Platform and version information
- Your OS: Red Hat Enterprise Linux 7.
- Your Ruby version:
- Your version of Puppet: Puppet Enterprise 5.5.10
- Your version of Sensu: 5.16.1
- Your version of this module: 4.4.1

## Anything else to add that you think will be helpful?
It's traceable to PR #1207 where the parameter was introduced

**Comment by treydock** [comment]
Do you use environment caching for types? 

Could try running puppet on puppetserver then restarting puppetserver to see if it will load new type parameter. If you're using type caching then you need to run commands to update your cache.

**Comment by treydock** [comment]
Also just realized that one issue with Puppetserver is if you're not using type caching then type parameters don't always respect environment isolation so the available properties for a type might come from a different environment.

https://puppet.com/docs/puppet/latest/environment_isolation.html

I use the command like they document where you do `puppet generate types ...` for all environments and this is only way I've found to ensure types from one environment do not affect other environments.

If you use r10k it's very easy to do this in a hook. I can provide ideas of how I do configured r10k if you use r10k.

**Comment by tdmike** [comment]
Hi,

We are not using environment caching for types, I'll test out the `puppet generate types` and see if that solves the problem. We do also use r10k so if it works I would love to know how you configure this in a hook.

**Comment by treydock** [comment]
These are bits from my `r10k.yaml`:

```
:postrun: ["/opt/osc/sbin/r10k-postrun.sh", "$modifiedenvs"]

:deploy:
  purge_levels:
  - environment
  purge_whitelist:
  - ".resource_types"
  - ".resource_types/**"
```

The purge levels setting maybe unnecessary, just something we switched to at one point. You do need to whitelist the `.resource_types` directories.

The script we use does a lot of things but the part specific to generating types:

```
environments=$1
config="/etc/puppetlabs/puppet/puppet.conf"
for environment in $environments; do
    logger -t r10k-postrun "/opt/puppetlabs/bin/puppet generate types --environment $environment --config $config"
    /opt/puppetlabs/bin/puppet generate types --environment $environment --config $config 2>&1 | logger -t r10k-postrun
done
```

**Comment by tdmike** [comment]
This seems to work fine, had in development for a few days now. You can close this one :+1:
