### ISSUE TITLE
Lost the ability to write custom attributes

### ISSUE THREAD

**Issue by bovy89** [sensu/sensu-puppet#1239]
Hi, I think we've lost the ability to write custom attributes, also used for token substitution in check definitions.

Previously, subscription "custom" attribute and sensu::write_json were used to write custom attributes, example:

```
sensu::write_json { "fpm-pool_${pool_name}":
    content => {
        'client' => {
            "fpm-pool_${pool_name}" => {
                'socket_path'   => $fpm_listen_path,
                'status_url'    => $status_location,
                'ping_location' => $ping_location,
                'ping_response' => $ping_response,
                'scheme'        => "${::fqdn}.php_fpm.${pool_name}",
            },
        },
    },
}

sensu::subscription {'disk-specific':
    custom => {
        disk_options  => '-i /data',
        disk_specific => {
            disk     => '/data',
            warning  => '90',
            critical => '93',
        },
    },
}

```

In sensugo, we should do the same thing using annotations and labels.

I think the fix done for subscription could also works great in this case (https://github.com/sensu/sensu-puppet/pull/1227, https://github.com/sensu/sensu-puppet/issues/1222)

**Comment by treydock** [comment]
There is no such way to add those custom items to subscriptions in Sensu Go, but you can add them to checks or entities.  Subscriptions are not resources in Sensu Go, they are strings assigned to entities and checks, so they can not have metadata.

For entities you'd either add this to the agent via `labels` and `annotations` parameters in `sensu::agent` class which writes to the agent YAML or you would add a `sensu_entity` resource with `labels` or `annotations`.

All Sensu Go resources that support labels and annotations also can have them in this module. The resources in your examples have no Sensu Go equivalents that I'm aware of so this is a limitation of Sensu Go or just something that has to be done a different way.  I can't tell from your example what the `fpm-pool` is but if it's a custom client you'd have to replicate that with `sensu_entity` resource.

**Comment by bovy89** [comment]
Hi, 

Let me explain. The fix done for subscription (see #1183, #1227, #1222) maybe could also works great in this case. This is crucial for feature-parity with sensuclassic, example:


Sensu classic (before):
```
sensu::subscription {'disk-specific':
    custom => {
        disk_options  => '-i /data',
        disk_specific => {
            disk     => '/data',
            warning  => '90',
            critical => '93',
        },
    },
}
```


Sensu go (expected result):

```
sensu::agent::subscription { 'disk-specific': }

sensu::agent::label { 'disk-specific.disk_options':
  value => '-i /data',
}

sensu::agent::label { 'disk-specific.disk':
  value => '/data',
}

sensu::agent::label { 'disk-specific.warning':
  value => '90',
}

sensu::agent::label { 'disk-specific.critical':
  value => '93',
}

sensu::agent::annotation { 'mylabel':
  value => 'I <3 Sensu',
}
```


Without this, subscription are totally useless and checks parameters are not usable at all.

**Comment by treydock** [comment]
Subscriptions are still how you assign an agent to checks, so not entirely useless.  I will have to test to see if your idea of defining labels and annotations that way will work.  We are limited by what Puppet can do with the way Sensu Go expects to be configured so not as freely able to merge multiple sources of information.

**Comment by treydock** [comment]
@bovy89 See if #1240 does what you need.

**Comment by bovy89** [comment]
@treydock Perfect. It works. I also found that redact keywords does not works with nested key elements (labels, annotations), so I think the only feature we miss is the ability to add custom redact words:

Like that works great as default setting:

```
$redact_keywords  = ['password', 'passwd', 'pass', 'api_key',
                    'api_token', 'access_key', 'secret_key',
                    'private_key', 'secret', 'ec2_access_key',
                    'ec2_secret_key']

class { 'sensu::agent':
    <other_parameters>,
    config_hash  => {
        'redact' => $redact_keywords,
    },
}

# This is redacted
sensu::agent::annotation { 'password':
  value => 'supersecret',
}

```

But the following secrets are not redacted (maybe they should?):

```
sensu::agent::annotation { 'service_one.password':
  value => 'supersecret',
}

sensu::agent::annotation { 'service_two.password':
  value => 'supersecret',
}

sensu::agent::label { 'myservice.password':
  value => 'supersecret',
}
```

To achieve the redaction of these secrets, I think we need the same fix used for annotations and labels:
```
sensu::agent::redact {['service_one.password', 'service_two.password', 'myservice.password']: }
```

Maybe would also be useful to include that directly into annotation/label Puppet define:

```
sensu::agent::annotation { 'service_one.password':
  value  => 'supersecret',
  redact => true, # ---> this call sensu::agent::redact {'service_one.password': }
}

sensu::agent::annotation { 'service_two.password':
  value  => 'supersecret',
  redact => true, # ---> this call sensu::agent::redact {'service_two.password': }
}

sensu::agent::label { 'myservice.password':
  value  => 'supersecret',
  redact => true, # ---> this call sensu::agent::redact {'myservice.password': }
}
```

What do you think?

**Comment by treydock** [comment]
I think a redact parameter might be too many layers of abstraction. What you can do now is this:

```
sensu::agent::config_entry { 'redact-service_one.password':
  key    => 'redact',
  value => ['service_one.password'],
}
sensu::agent::config_entry { 'redact-service_two.password':
  key    => 'redact',
  value => ['service_two.password'],
}
```

You'd still want to pass an array of redacted keywords via agent class.  This should work as datacat functionality we are using will merge array values.

**Comment by bovy89** [comment]
Ok thanks. It works.

**Comment by treydock** [comment]
@bovy89 The idea of a `redact` parameter was added in #1241
