### ISSUE TITLE
Unknown resource type: 'datacat_collector'

### ISSUE THREAD

**Issue by solomson** [sensu/sensu-puppet#1246]
## Description of problem

- What did you do? puppet agent -t on a node controlled by puppet, using the sensu module
- What happened? Error stating that "datacat_collector" resource type is unnknown
- What did you expect to happen? No issues
- How can someone reproduce the problem? Unsure, the issue does not occur in the module version 4.2.0. Assuming just use the latest sensu puppet module with minimal config on centos 7/8.

## Command used and debugging output

- What does your puppet config look like (including any hiera config)

- Is this a masterless or master based puppet setup? Master based

Error output from running puppet agent -t on node:
```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evalua
ting a Resource Statement, Unknown resource type: 'datacat_collector' (file: /etc/puppetlabs/code/environments/development/mo
dules/sensu/manifests/agent.pp, line: 197, column: 3) on node ...
```
Below are the lines 189-209 in the /etc/puppetlabs/code/environments/development/mo
dules/sensu/manifests/agent.pp file found on the master:
```
  package { 'sensu-go-agent':
    ensure   => $_version,
    name     => $package_name,
    source   => $_package_source,
    provider => $package_provider,
    before   => File['sensu_etc_dir'],
    require  => $sensu::package_require,
    notify   => Service['sensu-agent'],
  }

  datacat_collector { 'sensu_agent_config':
    template_body   => '<%= @data.to_yaml %>',
    target_resource => File['sensu_agent_config'],
    target_field    => 'content',
  }

  datacat_fragment { 'sensu_agent_config-main':
    target => 'sensu_agent_config',
    data   => $config,
    order  => '01',
  }
```

## Platform and version information

- Your OS:  CentOS 8.1
- Your Ruby version: ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux]
- Your version of Puppet:  open source 6.9.3, dockerized
- Your version of Sensu:  5.19.0
- Your version of this module:  4.10.0

## Anything else to add that you think will be helpful?

Also had this issue on module version 4.9.0. Works fine on 4.2.0. Unsure which version this error originates from.

**Comment by treydock** [comment]
We added a dependency on the datacat module: https://forge.puppet.com/richardc/datacat. You have to have that module present in your environment. This is a dependency in metadata.json of this module.

**Comment by solomson** [comment]
Adding that dependency seems to have solved it, thank you.
