### ISSUE TITLE
Trouble configuring CA / TLS for agents

### ISSUE THREAD

**Issue by solomson** [sensu/sensu-puppet#1247]
## Description of problem

- What did you do? puppet agent -t
- What happened?

Error "ERROR 500 on server: server error: no parameter named 'configure_trusted_ca_file ..."

- What did you expect to happen?

No need to explicitly trust a CA to use HTTPS. But looking at the docs, I should not get this error.
https://github.com/sensu/sensu-puppet/blob/master/REFERENCE.md#configure_trusted_ca_file

- How can someone reproduce the problem?

Connect agent node through this module to a sensu backend running in Kubernetes.

## Command used and debugging output

- What does your puppet config look like (including any hiera config)

```
sensu::resources::users:
  audun:
    ensure: present
    password: test123audun
    groups:
      - users
    configure: true
    configure_trusted_ca_file: "/data/sensu-aks-ca.crt"
```

- Is this a masterless or master based puppet setup? master based, dockerized

## Platform and version information

Your OS: CentOS 8.1
Your Ruby version: ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux]
Your version of Puppet: open source 6.9.3, dockerized
Your version of Sensu: 5.19.0
Your version of this module: 4.10.0

## Anything else to add that you think will be helpful?

What I want to achieve is to avoid HTTPS errors. I get "domain trusted by unknown CA errors".
I'm struggling to find a way to make this work. Sorry if this ticket is messy, I have tried multiple things.

My Sensu backend runs on a Kubernetes cluster available from the Internet, while my agents are on a on-prem network with Internet connectivity.

By default the "trusted_ca_file" points to /etc/sensu/ssl/ca.crt. This doesn't work for me. I therefore added a file per node which contains the CA to my backend. I can't seem to find a way to get the sensuctl commands run by puppet to use my custom ca.crt file, and I can't create a user using one either (see config)

I have also not been able to find an equvailent to  --insecure-skip-tls-verify from the sensuctl.

I've only had success connecting my entities to sensu backend by using manual changes. Every time the puppet agent runs through my sensu module, things are overwritten and typically don't work

The settings are in the file /root/.config/sensu/sensuctl/cluster

Setting either "insecure-skip-tls-verify": true,
or the trusted_ca_file works. The ca_file gets overwritten by the sensu puppet module, while the skip-tls seems to be left alone.

**Comment by treydock** [comment]
Where exactly are you getting the errors `domain trusted by unknown CA errors`?  The way sensuctl is configured is via `sensu::cli` class and `sensuctl_configure` resource.  You need to set `sensu:: ssl_ca_source` to the value that points to source of your custom CA and that will copy the file to /etc/sensu/ssl/ and that will get passed to sensuctl for trusting.  This module expects that if you are using SSL you are configuring Sensu with your certs and CA and to do that you must tell this module about your custom CA. Could try this:

```puppet
class { 'sensu':
  ssl_ca_source => '/data/sensu-aks-ca.crt',
}
```

The paths to the CA sensu uses in this module isn't configurable, what you have to do is ensure the contents of the sensu path contain your custom CA , like the example above does.

**Comment by solomson** [comment]
Correct, I tried this initially. I remember I was confused, not understanding why sensu didn't pick up my custom CA. I guess I never checked the file contents close enough. When the /etc/sensu/ca.crt file kept coming back and I couldn't see any mention in the logs of my file.. Anyways it works now, thank you.

On a side note, not related to this issue - I've had a fair amount of race condition issues for my sensu module. Most common is that sensu checks get created before backend URLS are configured. Turning into "error namespace default is not defined", which in turn makes the puppetdb go into an infinite crash loop. This might have changed after upgrading from module version 4.2 to 4.10 though.

**Comment by treydock** [comment]
If you run into the race condition issue using latest module version, please open an issue with some reproducible Puppet code using this module. The resources like `sensu_check` have automatic requirements set for their namespace and at one point we added validations that the name space is either defined in Puppet or exists in Sensu Backend before adding things like checks and assets.
