### ISSUE TITLE
Feature Request: Making dashboard-port flag available as a param to sensu::backend

### ISSUE THREAD

**Issue by amccrea** [sensu/sensu-puppet#1256]
Is it possible to get the --dashboard-port flag (listed here in the docs*) available to the sensu backend class? I don't want to run the UI on :3000, and I'd like to set this in puppet so I don't need to start the sensu backend up on the command line with --dashboard-port 443, for instance. 

* https://docs.sensu.io/sensu-go/latest/reference/backend/#configuration-summary

Thanks, 
Alison

**Comment by treydock** [comment]
You have two options.  Either adding the config option to backend.yml or add it to environment for sensu-backend.  All backend service flags have corresponding YAML option or environment variable option, at least in most cases.

```puppet
class { 'sensu::backend':
  config_hash => {
    'dashboard-port' => 443,
  },
}
```

Or

```puppet
class { 'sensu::backend':
  service_env_vars => {
    'SENSU_BACKEND_DASHBOARD_PORT' => 443,
  },
}
```

**Comment by amccrea** [comment]
Hi Trey, I am really sorry, I wasn't thinking -- I should have asked support if it was possible first (and RTFM...). Sorry for the noise, and thanks for the quick response!
