### ISSUE TITLE
Ubuntu 20.04 Focal compatibility

### ISSUE THREAD

**Issue by anamba** [sensu/sensu-puppet#1262]
I'm not sure this is a sensu-puppet issue exactly, but I'm not sure where to find more information.

I have a mixed fleet of Xenial, Bionic and Focal servers, and sensu is still not working on the Focal servers. I expected that in April (I recall it took some time to get Bionic support two years ago), but 4 months later, now I'm wondering if I'm doing something wrong.

The main symptom on Focal is that apt can't find an installable version of sensu-plugins-ruby, so no plugins can be installed.

Example output:

```
Error: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install sensu-plugins-ruby' returned 100: Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package sensu-plugins-ruby
Error: /Stage[main]/Sensu::Plugins/Package[sensu-plugins-ruby]/ensure: change from 'purged' to 'present' failed: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install sensu-plugins-ruby' returned 100: Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package sensu-plugins-ruby
Info: Stage[main]: Unscheduling all events on Stage[main]
Error: Could not find a suitable provider for sensu_plugin
```

`apt update` shows this:
```
E: The repository 'https://packagecloud.io/sensu/community/ubuntu focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by treydock** [comment]
That appears to be an issue with the packages provided by Sensu for the community repo: https://packagecloud.io/sensu/community.  I do not see any packages for Ubuntu Focal.

I'd recommend asking for Sensu to build Ubuntu Focal packages here: https://github.com/sensu/sensu-plugins-omnibus/issues

**Comment by ghoneycutt** [comment]
@anamba Thanks for telling us about this, though as Trey mentioned, please open an issue with Sensu so they can track this and make it part of their automated build.

We saw a similar issue with EL8 and found that the packages from EL7 worked fine. Suggest trying the packages from Ubuntu 18.04 LTS and see if that works in the interim.

**Comment by anamba** [comment]
Thanks for the ideas. So it turns out the bionic package does indeed work. I installed that and set `sensu::plugins::manage_repo: false` in hiera (focal only) and my puppet runs are green again.

**Comment by anamba** [comment]
A final update: I noticed that the packagecloud repo updated a few days ago and now includes a Focal build. So this issue is now fully resolved, no workarounds needed.
