### ISSUE TITLE
sensu Web UI community version installation support

### ISSUE THREAD

**Issue by maxadamo** [sensu/sensu-puppet#1263]
## information request

will you support the installation of the new Sensu Web UI for the community version: https://github.com/sensu/web ?
This is being used in the community version only and I wonder whether I should wait for you to add this component to the puppet module, or f I need to do it myself.

**Comment by treydock** [comment]
That's something I was planning to add as we add changes to support Sensu Go 6.  There is a pull request already open at #1255 for initial Sensu Go 6 changes to this module.  If the web addition doesn't make it into that pull request, it will be added to a new one shortly after #1255 is completed.

**Comment by ghoneycutt** [comment]
@maxadamo please read the comment from @portertech in https://github.com/sensu/sensu-puppet/pull/1267

The code is still available and we recommend that you add it to a profile class. This way you will not fork the sensu module and can continue to update it.

**Comment by maxadamo** [comment]
Thanks @ghoneycutt . Really appreciated. 
The manifest works pretty well... and perhaps it can be turned onto a public module on Forge, maintained by community. 
I give it a try. Thanks a lot.

**Comment by maxadamo** [comment]
there we go: https://forge.puppet.com/maxadamo/sensu_web :see_no_evil: 
Please let me know if you've any problem with credits and mentions in that page.
