### ISSUE TITLE
backend init fails when using non-default etc_dir

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-puppet#1295]
## Description of problem

Execution of `sensu-backend init` fails when using a non-default value for `sensu::etc_dir`

## Anything else to add that you think will be helpful?

Around https://github.com/sensu/sensu-puppet/blob/v5.5.0/manifests/backend.pp#L377-L392 I think the `--config-file` flag should be used to explicitly specify path to `${sensu::etc_dir}/backend.yml`.

**Comment by ghoneycutt** [comment]
Thank you for submitting this along with the great explanation. We are looking into it.

**Comment by ghoneycutt** [comment]
@cwjohnston This is fixed as of v5.5.1
