### ISSUE TITLE
Some descriptions are missing

### ISSUE THREAD

**Issue by ghoneycutt** [sensu/sensu-puppet#1300]
Running `pdk bundle exec rake reference` shows the following descriptions are missing.

```
[warn]: Missing a description for Puppet resource property 'ensure' at lib/puppet/type/sensu_agent_entity_config.rb:57.
[warn]: Missing description for param 'namespace' in Puppet Task resolve_reference.
[warn]: Missing description for param 'subscription' in Puppet Task resolve_reference.
[warn]: Missing description for param 'interface_list' in Puppet Task resolve_reference.
[warn]: Missing description for param 'uri_ipaddress' in Puppet Task resolve_reference.
```

**Comment by treydock** [comment]
Just FYI that the standard release process should not require executing `rake reference` manually. That is handled by `rake release` which is what's documented in CONTRIBUTING.md.  I will fix those warnings, some of them are real some are bugs in the code.
