### ISSUE TITLE
Standalone checks are default true?

### ISSUE THREAD

**Issue by matthewbarr** [sensu/sensu-puppet#144]
Readme implies that all checks are default standalone=false.  

Code is currently asserting that standalone=true is the default.

**Comment by s33dunda** [comment]
I know this was closed long ago. But I just ran into this again. 
https://sensuapp.org/docs/latest/reference/checks.html#check-attributes
the default says false. But the sensu sets it to true by default.

**Comment by ghoneycutt** [comment]
@s33dunda To which check attribute are you referring?
