### ISSUE TITLE
Add functionality to configure mutators

### ISSUE THREAD

**Issue by max-koehler** [sensu/sensu-puppet#230]
If i see it right, currently we can't create configurations for mutators with the puppet modul.
Checks, config, handlers, subscriptions, ... everything can be configured except the mutators.

Is there any possibility to configure it with puppet?

**Comment by confiq** [comment]
> You can configure it via the handler type - https://github.com/sensu/sensu-puppet/blob/master/lib/puppet/type/sensu_handler.rb#L67. Thanks!

@jamtur01 : I think he was referring to configuring mutator and not a handler (ex: http://sensuapp.org/docs/0.16/mutators). 
With [sensu_handler](https://github.com/sensu/sensu-puppet/blob/master/lib/puppet/type/sensu_handler.rb#L67) you are able to configure only the handler but not the mutator. This issue should be open.

CC: @max-koehler @aamerik

**Comment by max-koehler** [comment]
:+1:

**Comment by jamtur01** [comment]
PR welcomed. Thanks!

**Comment by confiq** [comment]
I'm not sure by PR you meant Public Relationship in this case....
If nobody started to work on this issue you might assign it to me and I'll try to make PR. 
It should not be hard to do...

**Comment by jlambert121** [comment]
PR meaning Pull Request.  With the github model if someone forks the repo, makes changes/improvements/fixes they can send those changes back to the upstream repo through a Pull Request.

**Comment by confiq** [comment]
"/s" meant to be sarcasm.
I'm sorry, it supposed to be bad joke...

**Comment by jaxxstorm** [comment]
I believe this is merged and resolved, so closing. Please reopen if required.
