### ISSUE TITLE
Could not load downloaded file /var/lib/puppet/lib/puppet/provider/sensu_client_config/json.rb: no such file to load -- rubygems

### ISSUE THREAD

**Issue by Jinkxed** [sensu/sensu-puppet#256]
OS: Amazon Linux AMI
Ruby Version: 2.0.0p481
Puppet Version: 2.7.25

Error:  Could not load downloaded file /var/lib/puppet/lib/puppet/provider/sensu_client_config/json.rb: no such file to load -- rubygems

$> ls -alh /var/lib/puppet/lib/puppet/provider/sensu_client_config/json.rb
-rw-rw-r--  1 root root 2.3K Sep 30 18:46 json.rb

rubygems is installed
ruby-devel is installed
json gem is installed

pluginsync is enabled

Set up is exactly as described in the Readme with heira files etc.

Any hints would be appreciated!

**Comment by confiq** [comment]
I'm having similar problem here...
