### ISSUE TITLE
Support for multiple broker connection options with RabbitMQ

### ISSUE THREAD

**Issue by royalj** [sensu/sensu-puppet#269]
Since Sensu 0.15 multiple broker connections with RabbitMQ have been supported to provide cluster failover without the need for a load balancer. It would be nice if this could be supported in the puppet module as well so we can start utilizing this feature.

**Comment by jamtur01** [comment]
I haven't had a chance to address this and it's unlikely I will. I'd be happy to take a patch replacing the provider with a template.

**Comment by agoddard** [comment]
@dblessing did you end up having a play with this?

**Comment by roobert** [comment]
Hi, I came here looking for this feature since it's now the recommended method to do HA Sensu.

I forked 2.0.0 (I tried forking master but was getting various errors) and adjusted the `sensu::rabbitmq::config` class to use a template if `sensu::rabbitmq_hosts` is set which should maintain backwards compatibility for existing deployments and allow people to define multiple servers if they need to.

In terms of implementation detail: the template first checks for unique configuration per-node and then falls back to checking for common values since it's assumed that when using rmq in a cluster configuration you'll have configured each server with the same certs, etc.

I'm not sure whether I should open a PR for this or not since it probably needs rebase'ing and I haven't added any tests or anything. Opinions welcome.

Cheers,

**Comment by dalesit** [comment]
I've spun up the Vagrant instance, copied in the changes to the module, and added the lines
``` 
   use_embedded_ruby => true,
   rabbitmq_hosts    => ['localhost','puppet'],
```
to the sensu-server.pp file in tests.

Doing a `puppet apply sensu-server.pp` generates this error:
```
Error: Evaluation Error: Error while evaluating a Function Call, Failed to parse template sensu/rabbitmq.conf.erb:
  Filepath: /etc/puppet/modules/sensu/templates/rabbitmq.conf.erb
  Line: 5
  Detail: undefined method `has_key?' for "localhost":String
 at /etc/puppet/modules/sensu/manifests/rabbitmq/config.pp:125:18 on node sensu-server.example.com
Error: Evaluation Error: Error while evaluating a Function Call, Failed to parse template sensu/rabbitmq.conf.erb:
  Filepath: /etc/puppet/modules/sensu/templates/rabbitmq.conf.erb
  Line: 5
  Detail: undefined method `has_key?' for "localhost":String
 at /etc/puppet/modules/sensu/manifests/rabbitmq/config.pp:125:18 on node sensu-server.example.com
```
Any thoughts on where the error might be?

**Comment by roobert** [comment]
The format of your configuration is incorrect. `rabbitmq_hosts` expects a hash, see the template: https://github.com/roobert/sensu-puppet/blob/sensu_multi_rmq/templates/rabbitmq.conf.erb

Here's a (valid) example hiera config:

```
sensu::rabbitmq_hosts:
  - host: "sensu0.xxx.net"
    ssl: true
  - host: "sensu1.example.net"
    ssl: true
  - host: "sensu2.example.net"
    ssl: true
```

**Comment by cwjohnston** [comment]
@roobert I'm very interested in seeing rabbitmq host configurations as an array be supported by this module. Any chance you'll be opening a PR?

**Comment by roobert** [comment]
@cwjohnston: my patch would need tests adding and to be rebased against master which I'm hesitant to do before @jlambert121 / @jamtur01 comment on implementation. I'm also not confident that this is the best way or even a good way to implement this functionality, I just needed something that worked quickly. Since this issue has been open for over a year I don't want to do additional work on this unless I know it'll be worth while, i.e: merged into master.

**Comment by jlambert121** [comment]
@roobert without seeing the patch (there isn't a PR I missed is there?) I can't say for 100% certainty that I'd merge it, but I'm not opposed to the feature.  If it isn't a breaking change and is written similar to the rest of the code base with tests, it should be an easy thing to get in.  If it is a breaking change, we'd need to make it part of a 3.0 release.

**Comment by roobert** [comment]
@jlambert121, ah, I linked to my fork but not an actual diff, here's the changes I made to the 2.0.0 release: https://github.com/roobert/sensu-puppet/compare/bd58e836f7959a9475ffc9d0dcda8bfbf055987d...master

**Comment by jlambert121** [comment]
@roobert I totally missed the link to your fork, thanks for making it obvious for me.  

I'm fine with this approach.

I wonder if it makes sense to just drop the `sensu_rabbitmq_config` type/provider so we don't have two paths for configuring the same file (if `rabbitmq_hosts` is unset it would be easy enough to build the single host into an array and deprecate those settings).  I can do that refactor later too if you want.

**Comment by roobert** [comment]
@jlambert121 that makes sense to me. Feel free to refactor or whatever, I'm not precious. If you'd like me to make initial changes or anything then let me know how I can help and I should be able to get to it next week.

**Comment by dalesit** [comment]
I've made some changes based on Rob's fork which allows either providing a hash with settings, or just an array of servers utilising the same settings as set for a single host. 

It is in the cluster_config branch of my fork below. I am in the process of updating the vagrant files to test with a cluster. 

It uses a Boolean $rabbitmq_cluster to determine whether to use $rabbitmq_cluster_hosts as an array of servers, or $rabbitmq_cluster_custom as an array of hashes (using Rob's approach). 

The $rabbitmq_cluster_hosts also works as an array of one. 

https://github.com/dalesit/sensu-puppet/tree/cluster_config?files=1

**Comment by dalesit** [comment]
#485 raised - comments and suggestions welcome...

**Comment by roobert** [comment]
There's a bit more discussion on the ticket @dalesit referred to for those that are interested..

**Comment by dalesit** [comment]
Just merged in the latest changes from #490 into #485

**Comment by gbolo** [comment]
let's get these pulls merged. We really need support for multiple rabbitmq servers in the sensu puppet module

**Comment by dalesit** [comment]
I've merged in the latest changes from #494 and #498 into #485  - not sure why, but some of the travis builds utilising Ruby 2.1.6 and Puppet 4 failed, but doesn't appear to be on anything I have touched - has there been a backend change which is causing these builds to fail? Previous builds worked fine.

**Comment by dalesit** [comment]
@jlambert121 is there something holding up this PR that I could work on? It would be useful to get support for multiple rabbitmq servers into the module, and this issue has been open for ages now...

**Comment by jaxxstorm** [comment]
Deprecated in favour of #581
