### ISSUE TITLE
Invalid parameter provider on Package[sensu-plugin]

### ISSUE THREAD

**Issue by brianwhigham** [sensu/sensu-puppet#308]
I'm unable to run puppet due to this error.  I'm new to sensu and the puppet plugin.  So, surely I'm just doing something wrong.  I'd appreciate any help.

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Invalid parameter provider on Package[sensu-plugin] at /etc/puppet/environments/production/modules-community/sensu/manifests/package.pp:51 on node

puppet client - 3.4.3
puppet server - 3.7.4
wget module - 1.5.7
stdlib module - 4.5.1
apt module - 1.7.0
foreman 1.7.2

**Comment by jlambert121** [comment]
What parameters are you passing sensu::plugin?

**Comment by brianwhigham** [comment]
I'm only using this:

class s_monitoring::client {
  class { 'sensu':
    rabbitmq_password     => 'mypass',
    rabbitmq_host         => 'myhost.fqdn',
    subscriptions         => ['default'],
  }
}


Thank you

**Comment by jlambert121** [comment]
@brianwhigham what version of the module are you using and what os are you using?  I'm not able to duplicate this error.

**Comment by brianwhigham** [comment]
I grabbed sensu-sensu-1.5.0 from the forge about a week ago.

# cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.1 LTS"
# uname -a
Linux ip-10-25-10-221 3.13.0-36-generic #63-Ubuntu SMP Wed Sep 3
21:30:07 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

I thought maybe I just hadn't run puppet on the master to have it pick
up it's providers.  But, I've now done that.  Same results.

Thanks

**Comment by jlambert121** [comment]
I attempted re reproduce this on ubuntu-server 1404.  You should be able to duplicate these results on your own machine if you check out this repo.

Check out version 1.5.0

```
git checkout 47a744a130602d577e51d9b158eef5c263645607
```

Install needed gems

```
bundle install
```

Run beaker to load the VM

```
BEAKER_destroy=no BEAKER_set=ubuntu-server-1404-x64 bundle exec rspec spec/acceptance
```

SSH to the VM 

```
cd .vagrant/beaker_vagrant_files/ubuntu-server-1404-x64.yml
vagrant ssh
```

Run your code:

```
sudo puppet apply -e "
class { 'apt': }
class { 'rabbitmq':
  ssl               => false,
  delete_guest_user => true,
}
-> rabbitmq_vhost { 'sensu': }
-> rabbitmq_user  { 'sensu': password => 'secret' }
-> rabbitmq_user_permissions { 'sensu@sensu':
  configure_permission => '.*',
  read_permission      => '.*',
  write_permission     => '.*',
}
class { 'redis': } ->
class { 'sensu': 
  rabbitmq_password => 'secret',
  rabbitmq_host => 'localhost',
  subscriptions => ['default']
}
"
```

Note in the above apt, rabbitmq, and redis are included so the sensu service starts and connects to everything.

From my run:
```
root@ubuntu-server-1404-x64:~# puppet apply -e "class { 'apt': }
> class { 'rabbitmq':
>   ssl               => false,
>   delete_guest_user => true,
> }
> -> rabbitmq_vhost { 'sensu': }
> -> rabbitmq_user  { 'sensu': password => 'secret' }
> -> rabbitmq_user_permissions { 'sensu@sensu':
>   configure_permission => '.*',
>   read_permission      => '.*',
>   write_permission     => '.*',
> }
> class { 'redis': } ->
> class { 'sensu':
>   rabbitmq_password => 'secret',
>   rabbitmq_host => 'localhost',
>   subscriptions => ['default']
> }
> "
Warning: Setting templatedir is deprecated. See http://links.puppetlabs.com/env-settings-deprecations
   (at /usr/lib/ruby/vendor_ruby/puppet/settings.rb:1139:in `issue_deprecation_warning')
Notice: Compiled catalog for ubuntu-server-1404-x64.ineu.us in environment production in 0.75 seconds
Notice: Finished catalog run in 2.16 seconds
```

I get the same result running from master instead of the 1.5.0 release.  I'm not sure what else I can do to troubleshoot this right now, what am I missing?

**Comment by jlambert121** [comment]
@brianwhigham I'm going to close this, if it is still an issue please let us know.
