### ISSUE TITLE
windows support

### ISSUE THREAD

**Issue by brettswift** [sensu/sensu-puppet#317]
it pains me to say this, but it'd be great to see windows support.  I've only tested sensu in vagrant/centOS environments, but I love it. 

In big enterprisey companies windows is very prevalent still.   If this module supported windows it would be a big help in the push to adopt sensu over big klunky enterprise software.

Does your team have this on your roadmap?  if not it would be good to know.   We may be able to contribute, but not sure on how soon we would be able to.

**Comment by jamtur01** [comment]
Our team is @jlambert121 and I in our spare time. :)

We have no plans for Windows support but would happily take a pull request if you build it.

**Comment by benh57** [comment]
I actually have done this already and integrated it into this module locally. I will put it together into a submittable state.

**Comment by jlambert121** [comment]
@benh57 did you have a chance to put together a PR?  We're going to do a major version release shortly and it would be great to include this if you had something.

**Comment by hurrycaine** [comment]
@benh57 Wanted to see how the windows integration is going?  I am going to have to do something similar and do not want to recreate the wheel.

thanks

**Comment by jlambert121** [comment]
I'm going to close this issue, but I would love to merge a PR for windows support if someone has some code.

**Comment by benh57** [comment]
Sorry for the delay, i'll get to this soon if no one else does.
