### ISSUE TITLE
New configuration: gem uninstall sensu-plugin  is failing in 1.5.0

### ISSUE THREAD

**Issue by brettswift** [sensu/sensu-puppet#318]
I have been building a vagrant box as my 'reference' configuration to learn sensu / grafana etc. 

I haven't touched this since version 1.3.1.   When I upgrade to 1.5.0, and build a clean vagrant box, the configuration I have isn't sufficient.   Version 1.3.1 however does work with my vagrant box. 

The `sensu-plugin`  gem should be installed under /opt/sensu/embedded......,  and it is.. however this script seems to want to uninstall it from the system ruby..   I'm not sure why? 

I have had a quick peek at the sensu-puppet code and I don't see an ensure => absent. 

### To recreate

1. clone this: https://github.com/brettswift/vagrant-sensu_example
2. Upgrade the version of sensu in the Puppetfile
3. run  `vagrant up sensuserver`. 

It may be my code, but nothing jumps out at me in the README documentation.   

Is this a bug? 

```
==> sensuserver: Error: /Stage[main]/Sensu::Package/Package[sensu-plugin]/ensure: change from 1.1.0 to absent failed: Execution of '/usr/bin/gem uninstall -x -a sensu-plugin' returned 1: ERROR:  While executing gem ... (Gem::InstallError)
==> sensuserver:     cannot uninstall, check `gem list -d sensu-plugin`
==> sensuserver:
==> sensuserver: Error: Execution of '/usr/bin/gem uninstall -x -a sensu-plugin' returned 1: ERROR:  While executing gem ... (Gem::InstallError)
==> sensuserver:     cannot uninstall, check `gem list -d sensu-plugin`
```

**Comment by pythianliappis** [comment]
+1. Also facing this issue on a real CentOS 6.5 installation using version 1.5.0 of the sensu puppet module.

    Error: Execution of '/usr/bin/gem uninstall -x -a sensu-plugin' returned 1: ERROR:  While executing gem ... (Gem::InstallError)

**Comment by pythianliappis** [comment]
It appears the default value in init.pp for `$sensu_plugin_version` is absent:

    $sensu_plugin_version     = 'absent',

So @brettswift just specify in your sensu server manifest file (or hiera conf) `sensu_plugin_version => 'installed'` and you should be ok.

The instructions for a basic installation on https://forge.puppetlabs.com/sensu/sensu need to be updated to reflect that as well.

**Comment by jamtur01** [comment]
@pythianliappis We'd welcome a PR with a docs update and/or a fix! Thanks!

**Comment by pythianliappis** [comment]
@jamtur01 Will do James!

**Comment by brettswift** [comment]
Yes I found the same thing... sorry I forgot to update this ticket.   The reference repo at the above link works on the master branch.  Thanks @pythianliappis

**Comment by queeno** [comment]
Hey folks,

I believe I found an issue in puppet resulting in the execution of `/usr/bin/gem uninstall -x -a sensu-plugin` rather than `/opt/sensu/embedded/bin/gem uninstall -x -a sensu-plugin`.

I have raised issue [PUP-4191](https://tickets.puppetlabs.com/browse/PUP-4191) in the puppet project and opened [PR #3708](https://github.com/puppetlabs/puppet/pull/3708) in puppetlabs/puppet.

I've also raised PR #332 in this project to work around this issue.

Could you please retest `sensu/sensu-puppet` with my workaround in place?

Thanks!

**Comment by ianjs** [comment]
I got bitten by this too, and it makes me wonder why it defaults to 'absent'? 

I would have thought installing the sensu-plugin gem would have been the most likely use case, especially as excluding it means a newbie will be scratching their head as to why it doesn't Just Work.
