### ISSUE TITLE
Unable to purge handlers, extensions, or mutators

### ISSUE THREAD

**Issue by nhinds** [sensu/sensu-puppet#328]
Since #302 was reverted in #307, #321 has been merged which supposedly re-added this functionality. However the following directories are not purged with this new implementation:
`/etc/sensu/handlers`, `/etc/sensu/extensions`, `/etc/sensu/mutators`, `/etc/sensu/extensions/handlers`

I'm willing to go and create another PR to re-add this functionality, but before I do I'd like to know your preferred approach. Would you like the new parameter `purge_plugins_dir` to purge these additional directories (possibly also renaming the parameter), or would you like 4 additional parameters to purge these 4 directories? Or something in between?

**Comment by nhinds** [comment]
Ping: @jlambert121 do you have a preference for an approach to re-add this functionality?

In my setup all handlers/extensions/mutators are managed by puppet, and I need unmanaged handlers/extensions/mutators to be purged. I'd like to know your preference before submitting another PR.

**Comment by jlambert121** [comment]
I was looking at this last week and I hate to have a ton of different parameters that all change slightly different things.  Just as a point of discussion, what about a purge hash?

```
purge => { 
    'plugins'  => false, 
    'config' => true,
    'handlers' => true,
    'extensions' => false
}
```

Do you think that's getting too confusing for people?  It would be nice to confine the parameter creep though.

**Comment by jhoblitt** [comment]
I suspect most people would want to purge everything so I'm not sure how much value there is in fine grain control.

**Comment by nhinds** [comment]
My original PR for this was a single "purge everything" flag, and that was reverted because in #304 somebody didn't want to purge everything.

I think that a hash would be doable, and avoid adding tons of new parameters.

Do you reckon the existing parameters should be removed, fail if they're specified, or continue to work to retain backwards compatibility? For prior art, I see that the `sensu::dashboard` parameter currently fails if it's specified, so we could do a similar thing. Alternatively we could ensure they continue to work, but warn if they're used (so they can be removed later) - which is more work but less surprising for callers, I guess?

**Comment by nhinds** [comment]
Re: wanting to purge everything, we could make `sensu::purge` accept a `true`/`false` value in addition to the hash, so people who wanted to purge everything could use:

    purge => true

People who wanted to purge nothing could use the default (or `purge => false`), and people who want to purge configuration and plugins without purging handlers could use the hash form:

````
purge => {
    plugins => true,
    config => true
}
````

**Comment by nhinds** [comment]
Raised #401 with an implementation which accepts booleans or a hash, and fails if you pass `purge_config`/`purge_plugins_dir`.

I made another branch which just warns when `purge_config`/`purge_plugins_dir` are specified, but I think it makes the logic more confusing when you have to understand how a global purge parameter and individual purge parameters interact with each other. Code is at 7b1d7a81bf7ff95d03b1f76776d149e48eb4efee

**Comment by jlambert121** [comment]
Nice!  I like #401.  It adds a little bit of complexity, but the code is easy to read and most of it is hidden from the average user.  Unless anyone has a different implementation idea in the near future I'm going to merge this one.
