### ISSUE TITLE
operatingsystemmajrelease is lsbmajdistrelease in puppet 3

### ISSUE THREAD

**Issue by josephmc5** [sensu/sensu-puppet#330]
One of the facters that is not compatible with puppet 3. The factor operatingsystemmajrelease is lsbmajdistrelease in puppet 3. This breaks the yum manifest and possibly other areas. 

modules/sensu/manifests/repo/yum.pp
```
class sensu::repo::yum {

  if $caller_module_name != $module_name {
    fail("Use of private class ${name} by ${caller_module_name}")
  }

  if $sensu::install_repo  {
    if $sensu::repo_source {
      $url = $sensu::repo_source
    } else {
      if $::operatingsystemmajrelease == 7 {
          $url = $sensu::repo ? {
            'unstable'  => "http://repos.sensuapp.org/yum-unstable/el/6/\$basearch/",
            default     => "http://repos.sensuapp.org/yum/el/6/\$basearch/"
          }
      } else {
          $url = $sensu::repo ? {
            'unstable'  => "http://repos.sensuapp.org/yum-unstable/el/${::lsbmajdistrelease}/\$basearch/",
            default     => "http://repos.sensuapp.org/yum/el/${::lsbmajdistrelease}/\$basearch/"
          }
      }
    }


    yumrepo { 'sensu':
      enabled  => 1,
      baseurl  => $url,
      gpgcheck => 0,
      name     => 'sensu',
      descr    => 'sensu',
      before   => Package['sensu'],
    }
  }

}
```

**Comment by jlambert121** [comment]
What version of facter are you running?

**Comment by teran-mckinney** [comment]
A lot of CentOS machines don't have the LSB packages so this does not work on all systems. I generally do a split because I haven't found a better alternative that works everywhere.

https://github.com/thousandeyes/puppet-teagent/blob/master/manifests/repository.pp#L17

**Comment by jlambert121** [comment]
Trying to get some things wrapped up, it looks like operatingsystemmajrelease was introduced in facter 1.7 to remove the dependency on lsb* facts.  I'm going to close this out because I don't believe this module uses lsb* facts right now.
