### ISSUE TITLE
Creating checks with hiera

### ISSUE THREAD

**Issue by devopsprosiva** [sensu/sensu-puppet#354]
Hi,

How can I create client checks with hiera?

Thanks,
Siva

**Comment by bleuchtang** [comment]
Since https://github.com/sensu/sensu-puppet/commit/4722034b004905f8bbe138283c2d287d66b2c613 you can do this with:
---
sensu::checks:
  'file_test':
    command: '/usr/local/bin/check_file_test.sh'
classes:
    - sensu
