### ISSUE TITLE
Sensu_redis_config changes on every run

### ISSUE THREAD

**Issue by tizzo** [sensu/sensu-puppet#357]
I have an issue where both Sensu_redis_config and Sensu_client_config claim to change on every run despite the fact that the configuration doesn't actually seem to be changing.

Haven't started debugging yet but thought I'd open an issue for others encountering the same.

**Comment by warmfusion** [comment]
I've observed the same with keepalive config...
in my case:

Step 1 - Added a custom hash with tip = 'a string'
Step 2 - move tip to the common configuration (ie removed custom hash)

Symtoms are then:

```
Jun  4 15:34:25 srv puppet-agent[5617]: (/Stage[main]/Sensu::Client::Config/Sensu_client_config[srv.priv.example.com]/keepalive) keepalive changed 'custom => {"tip"=>"This box lives on physical1"}, handlers => ["default", "slack-high"], subdue => {"begin"=>"7PM UTC", "end"=>"7AM UTC"}, thresholds => {"warning"=>60, "critical"=>300}, tip => This box lives on physical1' to 'handlers => ["default", "slack-high"], subdue => {"begin"=>"7PM UTC", "end"=>"7AM UTC"}, thresholds => {"warning"=>60, "critical"=>300}, tip => This box lives on physical1'
```

But the configuration file does not change.

Manually removing the file, and running puppet replaces the file properly.

**Comment by warmfusion** [comment]
Readded a hash for custom and the constant changes went away.

**Comment by jlambert121** [comment]
I believe this is the issue that puppet < 4 doesn't have a true nil/undefined.  This should resolved in puppet 4 with puppet improvements.

**Comment by jlambert121** [comment]
@tizzo are you still having this issue on master?  There have been some provider fixes that hopefully have taken care of your issue.

@warmfusion removing attributes in puppet < 4 will have that issue - you have to manually go in and either remove the config from your generated files or just remove the generated files and let puppet remake them.

**Comment by jlambert121** [comment]
If you guys still have issues with this, please let us know.
