### ISSUE TITLE
allow merging of hiera configs instead of only taking lowest in hierarchy

### ISSUE THREAD

**Issue by countryHick** [sensu/sensu-puppet#366]
specifically for subscriptions and client-custom fields.

**Comment by pdaugavietis** [comment]
PR to follow (small change)

**Comment by rk295** [comment]
@pdaugavietis have you made this work yet? I've just come across this, and merging of classes would be fantastic.

**Comment by pdaugavietis** [comment]
i've got it working locally but not the tests :(   i'm refactoring now to
see if the tests pass as-is, and then i can add the additional stuff...

**Comment by pdaugavietis** [comment]
okay - PR is passing now, and functioning as desired locally as well.   thought i'd done this at least a week ago the first time, but now it's passing :)

**Comment by countryHick** [comment]
okay - this is now refactored to have 2 new options - $sensu::merge_{subscriptions,client_custom} that will merge all levels of hiera, instead of default taking lowest level as override(s)

**Comment by countryHick** [comment]
attacking this another way - closing ticket and pr
