### ISSUE TITLE
getting Notice: Do not use 'handle' and 'handlers' together. Your 'handle' value has been overridden with 'handlers'

### ISSUE THREAD

**Issue by pdaugavietis** [sensu/sensu-puppet#371]
i've defined handle: true, and a handlers array -- and getting this message:

Notice: Do not use 'handle' and 'handlers' together. Your 'handle' value has been overridden with 'handlers'

I'm guessing that i don't need to have both now?

**Comment by jlambert121** [comment]
Handlers takes an array of handlers https://github.com/sensu/sensu-puppet/blob/master/lib/puppet/provider/sensu_check/json.rb#L169 (and priority) over the single element handle (https://github.com/sensu/sensu-puppet/blob/master/lib/puppet/provider/sensu_check/json.rb#L169).  You only need one of the two, correct.
