### ISSUE TITLE
need updates to support subdue and possibly other new config sections

### ISSUE THREAD

**Issue by countryHick** [sensu/sensu-puppet#380]
going to look into the new(er) configs for sensu checks and such, and we'll see how far out of date we are :)

**Comment by jlambert121** [comment]
@countryHick find any others?  Any way you could send a PR for what you find?  We really need to release a new version - just want to get as much closed out first as possible.

**Comment by countryHick** [comment]
haven't looked much yet - but there are some odd handling around subscribers/standalone - but that might be on sensu side, not here (if i have an empty subscribers, it's not REALLY standalone) -- i'll try and get to this by Monday - i have some time tonight and tomorrow (hopefully)...

**Comment by jlambert121** [comment]
@countryHick I'm going to close this issue, but anything you run into that needs to be added please send a PR!
