### ISSUE TITLE
issue with "Do not use 'handle' and 'handlers' together. Your 'handle' value has been overridden with 'handlers'"

### ISSUE THREAD

**Issue by countryHick** [sensu/sensu-puppet#391]
In a nutshell - this doesn't make sens(u)e to me -- why was it added to say that if you have handlers, you can't diable the handling of a check?    I think it was added on commit #a9b4089cb3ff7ae28a56b8d6d535478953c8f6b8 but i don't agree with it.    I should accept whatever i tell it to do, and not impose a logic block - at least remove the 'return' there, and issue the warning for 'style' points or something.

https://github.com/sensu/sensu-puppet/blob/master/lib/puppet/provider/sensu_check/json.rb#L179

**Comment by jlambert121** [comment]
@countryHick I think this is because the handle attribute used to be used for "handler", but I could be mistaken - it's been a while.  A PR is likely warranted with an update to fix this.

**Comment by countryHick** [comment]
yeah - i'll make one later today methinks -- i've locally done this and works much better, cause now you can handle:false, aggregate:true - and your failed aggregates aren't alerting anymore :)

**Comment by jlambert121** [comment]
@countryHick I'm going to try to tag a 2.0 version of this module hopefully later this week.  Do you have a few minutes to do a PR for this?  I think a 2.0 version is the perfect time to correct this.

**Comment by countryHick** [comment]
hopefully - i'll try for today/tonight...

**Comment by jlambert121** [comment]
@countryHick Does #422 work for you?  I want to close this one out and then am going to tag a 2.0 release finally.

**Comment by countryHick** [comment]
Yep - that's the one
