### ISSUE TITLE
json providers can not "unset" properties

### ISSUE THREAD

**Issue by jhoblitt** [sensu/sensu-puppet#394]
Consider the following `sensu_check` resource declaration
```
  sensu_check { 'foo':
    ensure    => present,
    handlers  => 'bar',
    ...
  }
```
which should generate a check json file similar to:
```
{
  "checks": {
    "foo": {
      "handlers": [
        "bar"
      ],
      ....
    }
  }
}
```
If on a successive run, the `handlers` param is removed or set to 'undef'. e.g.:
```
  sensu_check { 'foo':
    ensure    => present,
    handlers  => undef,
    ...
  }
```
the handlers property is treated as unmanaged and the providers mutator method is never invoked.  This essentially means that manual editing or deletion of the configuration tree is the only way to unset previously set values.

Would it be reasonable to add a param to all of the json config generator types to have the provider purge unmanaged properties?

**Comment by jlambert121** [comment]
This is an issue with puppet 3.x where it is not able to determine an "unset" value in a type/provider since prior to puppet 4 there wasn't a true undefined type.  Are you running 3.x nodes?

**Comment by jhoblitt** [comment]
I've been whining about problems with `:undef` since the redmine days. :)  I'm not sure why the behavior is different with 4.x, I guess I'll have to look at the generated catalog.  Can you confirm this issue isn't present under 4?

**Comment by jlambert121** [comment]
While I am running puppet 4 I haven't actually verified it.

**Comment by jlambert121** [comment]
@jhoblitt have you tested this under 4.x?  Any results you can share?

**Comment by jlambert121** [comment]
Let me know if you're still seeing this issue under 4.x as well.
