### ISSUE TITLE
What version of puppet are you running?

### ISSUE THREAD

**Issue by jlambert121** [sensu/sensu-puppet#404]
I'm trying to get an idea what version of puppet everyone is running for testing on this module.  What version are you running?

**Comment by joshbeard** [comment]
Puppet Enterprise 3.8.2 here.  Module version in use tracks master.

**Comment by bovy89** [comment]
Puppet 3.8.2

**Comment by mnellemann** [comment]
Puppet 3.4.3, from Ubuntu 14.04.

**Comment by jbehrends** [comment]
On 3.7.4 but migrating to 4.2 shortly.

**Comment by mrolli** [comment]
Puppet 3.8.2

**Comment by nhinds** [comment]
Puppet 3.8.2

**Comment by smithtrevor** [comment]
Puppet 3.8.1 with parser = future and strict_variables = true

**Comment by brettswift** [comment]
metadata.json still articulates this module isn't compatible with puppet 4.   We will be upgrading soon, as anyone tested it there?

**Comment by jlambert121** [comment]
I'm running it with puppet 4, that should be updated.

**Comment by gsalisbury** [comment]
Puppet 3.8.3

**Comment by zbintliff** [comment]
3.6.2 on Amazon Linux.  We know there is a bug in this version of Puppet which only sets yum to default provider for ":operatingsystem => :redhat, :centos".  We have a fix and may PR it back once we test it in house first.

**Comment by jcochard** [comment]
Enterprise 3.8.2
