### ISSUE TITLE
Undefined variable "file_ensure" in sensu::handler

### ISSUE THREAD

**Issue by somic** [sensu/sensu-puppet#406]
https://github.com/sensu/sensu-puppet/blob/master/manifests/handler.pp#L145

$file_ensure variable seems to be defined within "if $source {" block and trips our handler of type='set' which doesn't have $source.

**Comment by jlambert121** [comment]
@somic can you check and make sure #417 resolves your issue?

**Comment by jlambert121** [comment]
#418 is the fix I should have written.
