### ISSUE TITLE
Please, push new version to forge with updated apt dependencies

### ISSUE THREAD

**Issue by maxstepanov** [sensu/sensu-puppet#413]
apt dependency was updated in June 26 but forge module wasn't updated yet.
it contains too strict dependency for apt and can't be overridden.
referencing github repo isn't possible in metadata.json.
Please update.

**Comment by danielbsh** [comment]
yes please do !!

**Comment by jlambert121** [comment]
I think just #424 is left to figure out and then I'll tag a 2.0 release.
