### ISSUE TITLE
Unable to set RabbitMQ Heartbeat option

### ISSUE THREAD

**Issue by warmfusion** [sensu/sensu-puppet#428]
The RabbitMQ configuration allows a `heartbeat` option to be provided which lets the sensu EM connection to RMQ to be held open even if the particular server gets no traffic, or runs through HAProxy (for example)

Can this option be added to the module?

**Comment by jlambert121** [comment]
This seems like a good parameter - would you take a stab at a PR?

**Comment by derkgort** [comment]
I just added the PR.

**Comment by jaxxstorm** [comment]
resolved by #559

**Comment by jeffmccune** [comment]
Closing this issue via #559 #596 and #623
