### ISSUE TITLE
manage_plugins_dir doesn't seem to do anything

### ISSUE THREAD

**Issue by jaxxstorm** [sensu/sensu-puppet#429]
I've set the manage_plugins_dir to false, and still the module keeps rewriting the perms on my /etc/sensu/plugins

Am I being crazy, or does this parameter not actually do anything?

**Comment by jlambert121** [comment]
What version of the module are you using?  

Whether or not the directory is managed is controlled by $_manage_plugins_dir (https://github.com/sensu/sensu-puppet/blob/master/manifests/package.pp#L114) which is ultimate controlled by the logic here: https://github.com/sensu/sensu-puppet/blob/master/manifests/init.pp#L392.

I don't see anything in the code that would change the dir perms if you set manage_plugins_dir to false, are you sure it's this module (maybe it's defined elsewhere?) and are you sure manage_plugins_dir = false is being assigned in this module?

**Comment by jaxxstorm** [comment]
Never mind, I was being silly. Jetlag fail.
