### ISSUE TITLE
Differentiate between sensu-plugin gem and the sensu-plugins

### ISSUE THREAD

**Issue by jaxxstorm** [sensu/sensu-puppet#432]
At the moment, there are two different things referred to as sensu-plugin.

There's the [sensu-plugin](https://github.com/sensu-plugins/sensu-plugin) framework which is required for stuff to work, and there's a parameter for it.

Then there's the sensu-plugin(s) which are optional scripts from from the community and such like. This is covered by a defined type

The documentation for these parameters isn't clear enough in my opinion and we need to ensure that people know the difference when reading the parameters list.

**Comment by jlambert121** [comment]
Yeah, the documentation could probably use some clarity there.  When it was last modified it was before the sensu plugin gems existed.  How about taking a whack at it?
