### ISSUE TITLE
Error: Could not convert change 'socket' to string: undefined method `keys' for nil:NilClass

### ISSUE THREAD

**Issue by poolski** [sensu/sensu-puppet#447]
As of the latest commit (merging #443), I get the error above every time I run Puppet. 

Any ideas?

**Comment by zbintliff** [comment]
Me too.

**Comment by zbintliff** [comment]
@poolski  I figured it out.  has to do with the "is_to_s" method when there was no bind previously.  So should only effect people updating.

The module itself is ok, its only when it tries to log (hence why it passes spec tests).  My quick and dirty was just to override the function on the host:

```
Notice: /Stage[main]/Sensu::Client::Config/Sensu_client_config[sensu1b-af93681f.coreeng.mlbam.dev.us-east-1.bamgrid.net]/socket: socket changed '' to {'bind' => '127.0.0.1', 'port' => '3030'}
```

**Comment by jlambert121** [comment]
This should be resolved, let me know if it isn't!
