### ISSUE TITLE
Repuppet fails

### ISSUE THREAD

**Issue by ortz** [sensu/sensu-puppet#469]
Hey,

I'm using sensu-puppet module with my vagrant environment for testing.
I've launched vagrant environment with the Vagrantfile within this module and everything works great.
I've launched additional vagrant server with this module (via Hiera), the first run is working great, but when I try to run provision again (changed configuration, added alerts/subscriptions and so on) it fails with the following:
==> default: Notice: /Stage[main]/Sensu::Api::Config/File[/etc/sensu/conf.d/api.json]: Dependency Sensu_rabbitmq_config[localhost.local] has failures: true
==> default: Warning: /Stage[main]/Sensu::Api::Config/File[/etc/sensu/conf.d/api.json]: Skipping because of failed dependencies
This error raises on each provider (rabbit, redis, client, server and so on).
When running puppet with --debug I noticed this message:
Debug: Puppet::Type::Sensu_check::ProviderJson: feature json is missing
Rubygems-json is installed and it doesn't explain how it worked in the first time, this is the only thing that I see in the debug that I thought might be relevant.

I'm running this module under CentOS7 with Puppet 3.8.1.

I've tried turning on and off the purging option, commenting the require JSON within the provider, nothing helps.

Any suggestions ?

**Comment by ortz** [comment]
Update; I have another module I'm using that installs stuff, when I run sensu module by itself it works (also repuppet), when it's combined with my module, it fails only at the second time.
I've tried to map what's wrong, and still couldn't find the real reason.
The rubygems-json is with the same version with or without my custom module.

**Comment by jlambert121** [comment]
@ortz it sounds like this is a conflict between modules, but there isn't enough information here to troubleshoot.  If this continues to be a problem, please provide some more information.  If you can do a vagrant image (and instructions) that shows the problem that would be about as perfect as it gets.
