### ISSUE TITLE
Release new version "Tag the repo"

### ISSUE THREAD

**Issue by EslamElHusseiny** [sensu/sensu-puppet#472]
A version bump is needed for sensu-puppet module to include latest updates.

**Comment by bovy89** [comment]
+1

**Comment by GhostLyrics** [comment]
To make this clearer: In order to use the new apt repository URL a new version of the puppet module must be released otherwise you keep using the 'repos' one instead of the new 'repositories'.

Stumbled across this while wondering that I have outdated versions.

**Comment by GhostLyrics** [comment]
@EslamElHusseiny could you edit the title to make it clear that the issue corresponds to the repo, please?

**Comment by caskolkm** [comment]
+1

**Comment by ttarczynski** [comment]
+1
The new release is also needed to use the updated yum repository URL.

**Comment by dmichelotto** [comment]
+1

**Comment by jlambert121** [comment]
2.1.0 finally released!
