### ISSUE TITLE
Wrong default value of rabbitmq_vhost

### ISSUE THREAD

**Issue by llauren** [sensu/sensu-puppet#473]
Hi,

It seems like a slash has dropped off the default value in https://github.com/sensu/sensu-puppet/blob/master/manifests/init.pp#L304 -- it should probably be `/sensu` not `sensu`.

Setting the value explicitly when calling `class { 'sensu': ... }` solved my keepalive problems :)

 ~llaurén

**Comment by dalesit** [comment]
Yes, this bit me as well...

**Comment by clintonm9** [comment]
@llauren I think I am having the same issue. My host are not connecting to RabbitMQ. How did you explicitly set the value?

**Comment by dalesit** [comment]
specify 
`                rabbitmq_vhost          => '/sensu',
 `
in the class definition

**Comment by clintonm9** [comment]
Yeah i got it, thanks!

**Comment by jaxxstorm** [comment]
So it looks like this was changed in this [commit|https://github.com/sensu/sensu-puppet/commit/4d00cc8cb7a8f4d9f74eb7d9ac4b5da5744122d0] way back in 2014. I'm happy to switch it back as we seem to have better support now for this.
