### ISSUE TITLE
Error no parameter named socket in sensu_client_config

### ISSUE THREAD

**Issue by mrodm** [sensu/sensu-puppet#474]
Using the master branch, an error appears related to socket parameter in resource sensu_client_config.
In this definition, I'm using default parameters.

`Error: Could not retrieve catalog from remote server: Error 400 on SERVER: no parameter named 'socket' at /etc/puppetlabs/code/environments/tbox_development/modules/sensu/manifests/client/config.pp:24 on Sensu_client_config[jtbox-mariorodriguez-fd2b.tuenti.local]`

I'm using Puppet 4.3.2 in a debian jessie (8.3)
Any suggestions?

**Comment by jlambert121** [comment]
Did you update to master from a previous version?  If so, did you restart your puppetmaster?

**Comment by jaxxstorm** [comment]
Yeah it's this bug: https://projects.puppetlabs.com/issues/8750

**Comment by mrodm** [comment]
Restarting the puppetmaster fixed it. After restarting this service, there were no errors about missing parameters.
Thanks!

**Comment by jlambert121** [comment]
Thanks for the follow up!
