### ISSUE TITLE
Sensu Windows: sensu_rabbitmq_config type needs base_path param passed

### ISSUE THREAD

**Issue by r0b0tAnthony** [sensu/sensu-puppet#489]
./manifests/rabbitmq/config.pp uses the sensu_rabbitmq_config provider but fails to pass it sensu::conf_dir variable,which has the OS dependent path, via base_path. This causes sensu_rabbitmq_config to fall back to /etc/sensu/conf.d. Additionally, this causes dependencies errors causing the setup of the service to fail.

config.pp simply needs to have the following added to the sensu_rabbitmq_config resource:
`base_path => $sensu::conf_dir`

**Comment by r0b0tAnthony** [comment]
#490

**Comment by jlambert121** [comment]
Closed with #490
