### ISSUE TITLE
Cannot create /etc/sensu/conf.d/redis.json without "password"

### ISSUE THREAD

**Issue by paramite** [sensu/sensu-puppet#503]
For cases where Redis instance is not password protected, it is impossible to setup Sensu, with this Puppet module, to connect to it because even when 'redis_password' is set to undef, the resulting config file contains "password": "".

**Comment by jaxxstorm** [comment]
I can't reproduce this with the latest version of the module, my `redis.json`

```
{
  "redis": {
    "port": 6379,
    "host": "sensuhost",
    "reconnect_on_error": true,
    "db": 0,
    "auto_reconnect": true
  }
}
```

Can you show the puppet code/hiera data you're using?

**Comment by paramite** [comment]
Back then I was not using latest version of the module. I will try to reproduce this with latest version and let you know.

**Comment by paramite** [comment]
Indeed, with latest version of the module, redis.json is created correctly. I'm closing the bug. Sorry for the noise.
