### ISSUE TITLE
Sensu puppet module causes invalid parameter prefetch on some runs of puppet

### ISSUE THREAD

**Issue by dmak1112** [sensu/sensu-puppet#504]
For some reason, after downloading the new sensu puppet module, puppet will randomly succeed or fail to run. Without changing any code, sometimes, puppet will run successfully, but most times, i receive this error:
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Invalid parameter prefetch on Sensu_rabbitmq_config
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

It will run normally for about 30 minutes every couple of hours based on testing.
Again, i am using the code directly from this repo. I've tried installing many different times, each with the same result.
I was using this version previously: https://github.com/dmak1112/kilo-puppet/tree/master/sensu
All dependences are within the required ranges

The only changes I made were:
I updated my sensu folder and update the purge paramater because mine was deprecated. my purge parameter now looks like this: purge => true

**Comment by dmak1112** [comment]
Updated description with some more information. Still having this issue.

**Comment by ttarczynski** [comment]
I've got the same error after updating the module to version 2.1.0:
```
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Invalid parameter prefetch on Sensu_rabbitmq_config[node.domain] at /etc/puppet/environments/env_name/modules/sensu/manifests/rabbitmq/config.pp:123 on node node.domain
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```

Version of puppet that I've used on puppet master: `puppet-3.7.4-1.el7.noarch`

I've tried to dig into what can cause this issue and found this puppet bug:
- [PUP-1515 – When compiling a catalog, providers should be loaded from specified environment](https://tickets.puppetlabs.com/browse/PUP-1515)
- [MODULES-1690 – Invalid parameter provider](https://tickets.puppetlabs.com/browse/MODULES-1690)

I've updated puppet on puppet master to version `puppet-3.8.7-1.el7.noarch` and now the error doesn't occur any more.

**Comment by dmak1112** [comment]
I updated the pupper version on my slave from 3.6.2 to 3.8.7. The master was already running 3.8.7. After this, I still get the error:

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Invalid parameter prefetch on Sensu_rabbitmq_config[compute-215.staging.moc.edu] at /etc/puppet/environments/staging_dimitri/modules/sensu/manifests/rabbitmq/config.pp:124 on node compute-215.staging.moc.edu-5afa8b7d-028a-4b6e-a299-acb8811a99b3
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

**Comment by jaxxstorm** [comment]
@dmak1112 I don't think this is necessarily a problem with the module. usually when types/providers are updated a restart of the master is required due to this: https://projects.puppetlabs.com/issues/8750

Can you confirm you've restarted your master when updating the module?

**Comment by zxjinn** [comment]
I was having this exact problem after updating the module, after a server restart things started working as anticipated. Puppet 3.8.6 on both client and master.

**Comment by jaxxstorm** [comment]
I think this is related to the bug I mentioned above. Going to close this, please reopen if you think it's an issue with the module itself.

**Comment by josephholsten** [comment]
if you run into this in the future, the remaining work seems to be in [SERVER-94](https://tickets.puppetlabs.com/browse/SERVER-94)
