### ISSUE TITLE
Travis builds failing even on no code change

### ISSUE THREAD

**Issue by dalesit** [sensu/sensu-puppet#511]
The Travis builds with Ruby 2.1.6 are all failing, regardless of code change (eg #510 which is not changing any code at all). It appears that all builds for Ruby 2.1.6 have failed since Travis build #922. I'm not sure what changed at that point.

**Comment by jaxxstorm** [comment]
The problem is related to the apt module and a `versioncmp` function call:

```
Puppet::PreformattedError:
       Evaluation Error: Error while evaluating a Function Call, 'versioncmp' parameter 'a' expects a String value, got Undef at /home/travis/build/sensu/sensu-puppet/spec/fixtures/modules/apt/manifests/params.pp:125:15 on node testing-worker-linux-docker-e3eb7565-3390-linux-2.prod.travis-ci.org
```

Basically the `lsbdistrelease` fact isn't set in the spec tests, so it's doing a `versioncmp` against an undef value, which seems to no longer be valid.

I have a fix on the way

**Comment by dalesit** [comment]
Excellent! That seems to have done the trick. Many thanks...
