### ISSUE TITLE
yum repository

### ISSUE THREAD

**Issue by driegel** [sensu/sensu-puppet#519]
What is the proper baseurl, which this module should install?
The documentation (https://sensuapp.org/docs/latest/platforms/sensu-on-rhel-centos.html) says:

0.25 baseurl=http://sensu.global.ssl.fastly.net/yum/$basearch/
0.23 baseurl=http://repositories.sensuapp.org/yum/$basearch/

Using the 0.23 repo URL, some installations automatically update,some don't.

Thanks!

**Comment by jaxxstorm** [comment]
repositories.sensuapp.org resolves to the fastly URL:

```
dig +short repositories.sensuapp.org                                                         
global.prod.fastly.net.
global-ssl.fastly.net.
fallback.global-ssl.fastly.net.
prod.a.ssl.global.fastlylb.net.
151.101.40.249
```

They are essentially the same thing
