### ISSUE TITLE
Using sensu_gem provider before sensu::client is installed?

### ISSUE THREAD

**Issue by daytonturner** [sensu/sensu-puppet#520]
Hi there,

So we're using this module with hiera, and found that when bootstrapping a new machine, doing the following generates an error:

```
sensu::client: true

system::packages:
     sensu-plugins-io-checks:
        ensure: installed
        provider: sensu_gem
```

What I end up with, is:

```Error: /Package[sensu-plugins-io-checks]: Provider sensu_gem is not functional on this host```

Until the sensu client has had a chance to install.  It's pretty straight forward, puppet is trying to satisfy the sensu_gem provided module, but its not going to work until the sensu client has been installed.

I tried adding a require: line and specifying things like Package[sensu] or Package[sensu-plugin] but just ended up with a circular dependency that could not be satisfied.

Removing the package from the config, letting sensu install, then running it afterwards works nicely, of course.

Any tips on how to get around this chicken and egg issue?

**Comment by jaxxstorm** [comment]
Use run stages:

https://docs.puppet.com/puppet/latest/reference/lang_run_stages.html

Have sensu install before the main stage and then the provider should be available

**Comment by jaxxstorm** [comment]
Going to close this, no feedback for several months.
