### ISSUE TITLE
Add some new maintainers

### ISSUE THREAD

**Issue by jaxxstorm** [sensu/sensu-puppet#522]
The speed this module moves at, considering the importance to the sensu community and the high usage doesn't really seem acceptable to me.

I would like to see some more maintainers added, or at least the current maintainers actively reviewing pull requests.

**Comment by jamtur01** [comment]
Are you volunteering? Happy to add anyone who is interested! Sadly, between $Dayjob, other projects L,  and family, current folks are pretty busy.

**Comment by jaxxstorm** [comment]
Yes absolutely, I would love to help.

**Comment by jamtur01** [comment]
Sure. I'll add you as a collaborator. Some rough rules @jlambert121 and I have been working off (and he's definitely done most of the recent work):

1. Nothing added without tests and documentation.

2. We're roughly SemVer - backwards incompatible interface/API changes require appropriate version bumps.

3. Best features for most number of users - avoid custom settings and configuration designed to address edge cases at the expense of ease of use.

**Comment by dalesit** [comment]
Great news. I have #485 waiting (since March) if someone could have a look - addresses #269 which has been open since November 2014!

**Comment by jaxxstorm** [comment]
Thanks! I'll get cracking on some of the backlog ASAP!
