### ISSUE TITLE
rake: uninitialized constant Syck with ruby 2.3.1

### ISSUE THREAD

**Issue by fessyfoo** [sensu/sensu-puppet#539]
running rake on ruby with a newer ruby results in an error `uninitialized constant Syck`

I realize that ruby > 2.1.6 is not in the [travis configurations](https://github.com/sensu/sensu-puppet/blob/a1d6fbf/.travis.yml#L11-L27)  but I thought I'd put this out there anyhow. 

```
% bundle exec rake validate
rake aborted!
NameError: uninitialized constant Syck
/Users/fess/check/ot/sensu-puppet/Rakefile:2:in `require' 
/Users/fess/check/ot/sensu-puppet/Rakefile:2:in `<top (required)>'
/opt/boxen/rbenv/versions/2.3.1/bin/bundle:23:in `load'   
/opt/boxen/rbenv/versions/2.3.1/bin/bundle:23:in `<main>' 
(See full trace by running task with --trace)
%
% ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
```

**Comment by jaxxstorm** [comment]
2.3.x isn't really supported by syck yet: https://github.com/ruby/syck/blob/master/syck.gemspec

And it's not entirely supported by Puppet yet:

https://docs.puppet.com/guides/platforms.html

I'll add support for 2.2, but we'll drop this and I'll fix #540
