### ISSUE TITLE
error while installing ruby_dep,  Bundler cannot continue

### ISSUE THREAD

**Issue by fessyfoo** [sensu/sensu-puppet#540]
when I run bundle using  any ruby version [listed in travis.yml](https://github.com/sensu/sensu-puppet/blob/a1d6fbf/.travis.yml#L11-L27)

i get an error from bundler about installing ruby_dep and it requiring a newer version of ruby. 

```
% bundle 
...
An error occurred while installing ruby_dep (1.4.0), and Bundler cannot continue.
Make sure that `gem install ruby_dep -v '1.4.0'` succeeds before bundling.
%
% gem install ruby_dep -v '1.4.0'
ERROR:  Error installing ruby_dep:
        ruby_dep requires Ruby version >= 2.2.5, ~> 2.2.
% 
% ruby -v 
ruby 2.1.6p336 (2015-04-13 revision 50298) [x86_64-darwin15.0]
```

if I run bundle with version 2.3 of ruby  and then run rake [I get an error about Syck](https://github.com/sensu/sensu-puppet/issues/539) https://github.com/sensu/sensu-puppet/issues/539

just trying to run the tests. :)

**Comment by jaxxstorm** [comment]
I'm gonna bump the whole travis config for the next release, to make sure we're testing with the right ruby versions :)

A PR would be appreciated.

**Comment by jaxxstorm** [comment]
Oh, I realised what you're doing now :)

```
bundle install --without system_tests development
```

Should work :)
