### ISSUE TITLE
rabbitmq HA solution

### ISSUE THREAD

**Issue by gauravyadav01** [sensu/sensu-puppet#541]
Hi , 

It would be great if you add rabbitmq HA config to this module. 

such as 

{
  "rabbitmq": [
    {
      "host": "10.0.0.6",
      "port": 5671,
      "vhost": "/sensu",
      "user": "sensu",
      "password": "secret",
      "heartbeat": 30,
      "prefetch": 50,
      "ssl": {
        "cert_chain_file": "/etc/sensu/ssl/cert.pem",
        "private_key_file": "/etc/sensu/ssl/key.pem"
      }
    },
    {
      "host": "10.0.0.7",
      "port": 5671,
      "vhost": "/sensu",
      "user": "sensu",
      "password": "secret",
      "heartbeat": 30,
      "prefetch": 50,
      "ssl": {
        "cert_chain_file": "/etc/sensu/ssl/cert.pem",
        "private_key_file": "/etc/sensu/ssl/key.pem"
      }
    }
 ]
}

**Comment by jaxxstorm** [comment]
This will be available when #518 is rebased and merged

**Comment by gauravyadav01** [comment]
thanks...

**Comment by jaxxstorm** [comment]
This is a duplicate of #269 so closing
