### ISSUE TITLE
Update Puppet Forge releases

### ISSUE THREAD

**Issue by poolski** [sensu/sensu-puppet#545]
While a whole load of work has been done on the module and a bunch of merge requests have been merged, the latest version is still stuck at 2.1.0 which is 8 months old.

Will you be pushing a new release to the Forge anytime soon?

**Comment by jaxxstorm** [comment]
Yes, we need to add the new features for 0.26 version of sensu first. I added a milestone to get this out the door.

**Comment by poolski** [comment]
@jaxxstorm any news on when the mythical 2.2.0 module will be released? 0.26 has been out for a pretty long while and none of us puppet users can upgrade because the module doesn't support 0.26 :cry:

**Comment by jaxxstorm** [comment]
@poolski I'm hoping to find some time to release it next week. I apologise for the delay. If you use the latest commit of this repo, it should work.

**Comment by jaxxstorm** [comment]
For those watching this, thanks for your patience. I hope to release a new module to the forge this weekend, time permitting.
