### ISSUE TITLE
subdue should be optional for sensu check definition

### ISSUE THREAD

**Issue by cabecada** [sensu/sensu-puppet#548]
because of this
https://github.com/sensu/sensu-settings/blob/37d22949f586015075de65881b61b5004bde9b55/spec/validator_spec.rb#L260

this
https://github.com/sensu/sensu-puppet/blob/master/manifests/check.pp#L180
would break.

we need to manage the hash to sensu_check { } that would filter out subdue attribute if not defined or empty hash

**Comment by ttarczynski** [comment]
@cabecada is what you need the same as described in: 
* [sensu::check unable to remove a check property #535](https://github.com/sensu/sensu-puppet/issues/535#issuecomment-246649982)

**Comment by jaxxstorm** [comment]
I think we need to completely rework the sensu subdue stuff for 0.26. I'd love someone to take a bash at this.

**Comment by cabecada** [comment]
root@sensu-server:~# cat /etc/puppet/modules/sensu/lib/facter/sensu_version.rb
require 'puppet'
Facter.add("sensu_version") do
  setcode do
    if Facter::Util::Resolution.which('dpkg-query')
      sensu_version = Facter::Util::Resolution.exec('dpkg-query --showformat=\'${Version}\' --show sensu')
    elsif Facter::Util::Resolution.which('rpm')
      sensu_version = Facter::Util::Resolution.exec('rpm -q sudo --qf \'%{VERSION}\'')
    end
  end
end

root@sensu-server:~# puppet apply -e 'notify {"${::sensu_version}": } '
Notice: Compiled catalog for sensu-server.example.com in environment production in 0.01 seconds
Notice: 0.26.1-1
Notice: /Stage[main]/Main/Notify[0.26.1-1]/message: defined 'message' as '0.26.1-1'
Notice: Finished catalog run in 0.04 seconds

a facter variable will help us take care of backward compatibity too :)

**Comment by cabecada** [comment]
something like this

```
root@sensu-server:~# cat  /tmp/foo.pp


notify { "${::sensu_version}": }

if "${::sensu_version}" < "0.26.1-1" {
  $subdue = {}
} else {
  $subdue = {
    'days' => {
      'all' => [
        {
          'begin' => '00:00',
          'end'   => '00:00',
        },
      ]
    }
  }
}

notify { "${subdue}": }
root@sensu-server:~# FACTER_sensu_version='0.25.5-1' puppet apply --modulepath /etc/puppet/modules /tmp/foo.pp
Notice: Compiled catalog for sensu-server.example.com in environment production in 0.02 seconds
Notice: 0.25.5-1
Notice: /Stage[main]/Main/Notify[0.25.5-1]/message: defined 'message' as '0.25.5-1'
Notice: {}
Notice: /Stage[main]/Main/Notify[{}]/message: defined 'message' as '{}'
Notice: Finished catalog run in 0.01 seconds
root@sensu-server:~# FACTER_sensu_version='0.26.1-1' puppet apply --modulepath /etc/puppet/modules /tmp/foo.pp
Notice: Compiled catalog for sensu-server.example.com in environment production in 0.02 seconds
Notice: 0.26.1-1
Notice: /Stage[main]/Main/Notify[0.26.1-1]/message: defined 'message' as '0.26.1-1'
Notice: {"days"=>{"all"=>[{"begin"=>"00:00", "end"=>"00:00"}]}}
Notice: /Stage[main]/Main/Notify[{"days"=>{"all"=>[{"begin"=>"00:00", "end"=>"00:00"}]}}]/message: defined 'message' as '{"days"=>{"all"=>[{"begin"=>"00:00", "end"=>"00:00"}]}}'
Notice: Finished catalog run in 0.01 seconds
```

**Comment by ttarczynski** [comment]
@cabecada there's a plan to handle compatibility with information in module docs: #568

Removing subdue property is now possible with syntax described here: #565

**Comment by cabecada** [comment]
+1

“absent” really makes sense over the default values :), and is really helpful too.
good work on this.

On Oct 31, 2016, at 11:53 AM, Tomasz Tarczynski <notifications@github.com<mailto:notifications@github.com>> wrote:


@cabecada<https://github.com/cabecada> there's a plan to handle compatibility with information in module docs: #568<https://github.com/sensu/sensu-puppet/issues/568>

Removing subdue property is now possible with syntax described here: #565<https://github.com/sensu/sensu-puppet/pull/565>

**Comment by jaxxstorm** [comment]
This is resolved!
