### ISSUE TITLE
Add support for deregister client config and deregistration handler

### ISSUE THREAD

**Issue by jaxxstorm** [sensu/sensu-puppet#550]
In sensu 0.25, the option to deregister a client was added: https://github.com/sensu/sensu/pull/1315

This should be added for the next version of the module

**Comment by jaxxstorm** [comment]
I don't think this is urgent for 2.2.0, we have support for this in the init script/sysconfig so it's working currently.

Still a nice to have though

**Comment by ghoneycutt** [comment]
Can you please provide a reference implementation with the path of the json file and its contents?

**Comment by cwjohnston** [comment]
@gh see https://sensuapp.org/docs/latest/reference/clients#deregistration-attributes for client configuration spec
