### ISSUE TITLE
Update subdue for 0.26

### ISSUE THREAD

**Issue by jaxxstorm** [sensu/sensu-puppet#553]
In 0.26, the subdue logic changed. It now only operates client side, and the hash config changed slightly.
- [x] Remove subdue from the handler side configuration
- [x] Add test coverage which covers the new handler specification on the check side
- [x] Make sure subdue can be removed from the config see #548 and #535

**Comment by ttarczynski** [comment]
@jaxxstorm I've tried to address the first two points in #563 and #564

**Comment by ttarczynski** [comment]
I've also tried to address the third point in #565
It allows to remove subdue with:
```
subdue => `absent'
```

**Comment by jaxxstorm** [comment]
@ttarczynski thanks for all the hard work!
