### ISSUE TITLE
$::sensu::purge['config'] causes file path error on Windows agents

### ISSUE THREAD

**Issue by joshbeard** [sensu/sensu-puppet#558]
If `$::sensu::purge['config']` is `true`, a Windows agent currently fails with:

> Error: Failed to apply catalog: Parameter path failed on File[/etc/sensu/dashboard.json]: File paths must be fully qualified, not '/etc/sensu/dashboard.json' at /etc/puppetlabs/code/environments/sensu_windows/modules/sensu/manifests/enterprise/dashboard/config.pp:27

The hardcoded file path (https://github.com/sensu/sensu-puppet/blob/master/manifests/enterprise/dashboard/config.pp#L27) is invalid.  This resource is in the catalog whether enterprise or not when `$::sensu::purge['config']` is true.

PR #544 will resolve it

**Comment by jaxxstorm** [comment]
There's a commit in there which updates the default vhost (again).

Once that is addressed, I'll merge.

**Comment by jaxxstorm** [comment]
This is resolved with the merge of #544
