### ISSUE TITLE
Allow remediation on check.pp

### ISSUE THREAD

**Issue by jonguijarro** [sensu/sensu-puppet#560]
Add remediation to  check.pp parameters.

Allowed parameters are:
command
ensure
type
handlers
standalone
interval
occurrences
refresh
source
subscribers
low_flap_threshold
high_flap_threshold
timeout
aggregate
aggregates
handle
publish
dependencies
ttl
subdue

Remediator can be set as a handler but cannot set params:
          remediation => {
            low_remediation => {
              ocurrences => [1,2],
              severities => [1],
              command => "/bin/bob"
              publish => false.  
            },
...
          }
Error 400 on SERVER: Syntax error at 'remediation'

**Comment by stevenviola** [comment]
It's not well documented, but I think in the check definition, you can pass a hash to custom, and that will show up as custom data included in each check. I think you would want your check to look like this:

```
sensu::check { 'check_ntp':
  command => 'PATH=$PATH:/usr/lib/nagios/plugins check_ntp_time -H :::ntp.server::: -w 30 -c 60',
  custom => {
    remediation => {
      low_remediation => {
        occurrences => [1,2],
        severities => [1],
        command => "/bin/bob",
        publish => false,
      } 
    }
  }
}
```

**Comment by cwjohnston** [comment]
I believe @stevenviola's comment is correct. Because` remediation` is not part of the [check definition specification](https://sensuapp.org/docs/latest/reference/checks#check-definition-specification), this handler configuration belongs under `custom`.

**Comment by ghoneycutt** [comment]
@Phil-Friderici could you please document this

**Comment by cwjohnston** [comment]
For clarity, any attribute that's not listed in the check definition specification belongs under `custom`.

**Comment by Phil-Friderici** [comment]
working on this in PR https://github.com/sensu/sensu-puppet/pull/739

**Comment by Phil-Friderici** [comment]
this issue can be closed now :)
