### ISSUE TITLE
does sensu-puppet work well in updating to 0.26 

### ISSUE THREAD

**Issue by cabecada** [sensu/sensu-puppet#561]
I have been trying endlessly to cleanly update sensu to 0.26 on windows 2012.
I just want a confirmation if someone updated sensu-client on windows to 0.26 ??

![image](https://cloud.githubusercontent.com/assets/20220560/19309174/edea9f00-90a0-11e6-925b-487a5e71667d.png)

**Comment by jaxxstorm** [comment]
Not at the moment, we have several changes needed before this is ready for 0.26.

**Comment by cabecada** [comment]
https://github.com/sensu/sensu/issues/1480

**Comment by jaxxstorm** [comment]
After speaking with several people over the last few weeks, I have it on good authority that this module supports 0.26 without issues.

It seems as @cabecada mentions, there _some_ issues with the windows agent, but I don't believe this is related to this module itself.

Closing this, please reopen if you feel this is incorrect.
