### ISSUE TITLE
Add github templates

### ISSUE THREAD

**Issue by jaxxstorm** [sensu/sensu-puppet#566]
Would be good to have a:
- [x] CONTRIBUTING.md
- [x] ISSUE_TEMPLATE.md
- [x] PULL_REQUEST_TEMPLATE.md

**Comment by ghoneycutt** [comment]
and code of conduct

**Comment by ghoneycutt** [comment]
code of conduct should just link to https://sensuapp.org/conduct so that the content is not duplicated.

**Comment by ghoneycutt** [comment]
@cwjohnston do you have PR template or CoC from another Sensu project we can pull in here?
