### ISSUE TITLE
Drop support for old versions of Puppet and Ruby in next major version?

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-puppet#577]
## Description of problem

- What did you do? Tried to add a feature
- What happened? Tests failed on older Puppet gem version/parser
- What did you expect to happen? Tests pass :)
- How can someone reproduce the problem? 

## Command used and debugging output

See failed builds here https://travis-ci.org/sensu/sensu-puppet/builds/172202862

## Platform and version information

- Your OS: 
- Your Ruby version: 1.8.7, 1.9.3, 2.0.0
- Your version of Puppet: 3.5 w/o future parser
- Your version of Sensu: 0.26
- Your version of this module: 6c927f695f521b875cf018cdb2f7791ea69745a1

## Anything else to add that you think will be helpful?

I'm not sure if this project aims to follow semantic versioning, but based on the published support schedules for [Puppet](https://puppet.com/misc/puppet-enterprise-lifecycle) and [Ruby](https://en.wikipedia.org/wiki/Ruby_(programming_language)#Table_of_versions), I believe its appropriate for this project to drop support for Puppet < 4.0 and Ruby < 2.0 in the next major version release. Although [Puppet 4.0 supports Ruby 1.9.3 and 2.0, it is not tested on these versions of Ruby](https://docs.puppet.com/puppet/4.0/reference/system_requirements.html).

Although I am motivated to submit this issue by the failure of a particular pull request, I think this change makes sense going forward for the project as a whole. 😉

**Comment by jaxxstorm** [comment]
Yes, I think at this stage we've added multiple conditionals to travis just for ruby 1.8.7, and it's becoming arduous.

I think the next release (2.2.0) will be the last that supports ruby 3.8.7. Does that seem acceptable?

**Comment by cwjohnston** [comment]
Makes sense to me 👍

**Comment by jaxxstorm** [comment]
Also, in addition to this, support for puppet 3.8.7 is EOL at the end of the year, so no more puppet 3 either, which means we can finally start using some of the Puppet 4 goodness.
