### ISSUE TITLE
etc_dir should be configurable

### ISSUE THREAD

**Issue by jaredledvina** [sensu/sensu-puppet#578]
## Description of problem
We're customizing the configuration directory of sensu and want to be able to set the etc_dir variable to a custom value. Looks like right now it's hard coded based on the OS type. 

This is the section I'm looking at: https://github.com/sensu/sensu-puppet/blob/master/manifests/init.pp#L525-L549

## Platform and version information

- Your OS: CentOS 6
- Your Ruby version: 
- Your version of Puppet: Open Source Puppet 3.8
- Your version of Sensu: 0.26.5
- Your version of this module: Latest

**Comment by jaxxstorm** [comment]
Agreed, a PR would be appreciated!

**Comment by Phil-Friderici** [comment]
This is the section jaredledvina was looking at the 4th November 2016:
https://github.com/sensu/sensu-puppet/blob/93b2c2bdddb4ab7b221f11002f85ddd9bce04675/manifests/init.pp#L525-L549

**Comment by Phil-Friderici** [comment]
working on this in PR https://github.com/sensu/sensu-puppet/pull/741

**Comment by ghoneycutt** [comment]
Thanks for all your help!

Released in v2.28.0
