### ISSUE TITLE
REQ - Windows - Support chocolatey as a package manager

### ISSUE THREAD

**Issue by tomasquith** [sensu/sensu-puppet#589]
I'm looking to deploy on windows, into a pretty locked down environment - I've noticed that the package.pp gets the client MSI from the internet with no override.

I'd propose using chocolatey as a method of retrieving this for windows, however a package would be needed to be created for the MSI. Ideally, sensu would host a nuget feed with packaged versions of their MSIs, then we could rely on that or a local package feed if required.

I imagine there aren't many windows users of sensu, especially with more locked down environments, but I just thought I'd make my thoughts known. 

I'll take a look at the work required.

**Comment by jaxxstorm** [comment]
> however a package would be needed to be created for the MSI

This probably falls under the scope of the sensu project.

If we get this from them, there's nothing stopping this being an option, but not sure it falls under the scope of this module.

**Comment by tasquith** [comment]
Cheers @jaxxstorm - I'll raise an issue on the main sensu repo to try and start a conversation :)

**Comment by jpuskar** [comment]
How about providing a variables in sensu::package like 'pkg_provider', and 'pkg_source'?
Then we could set sensu::package::pkg_provider: 'chocolatey', and the source accordingly.

**Comment by ghoneycutt** [comment]
Released in v2.18.0
