### ISSUE TITLE
new subscribe check does not restart sensu-api service

### ISSUE THREAD

**Issue by giedriusramas** [sensu/sensu-puppet#600]
## Description of problem

- What did you do?
Adding new check:
  sensu::check { 'metrics-disk-capacity.rb':
    type        => 'metric',
    handlers    => 'relay',
    command     => 'metrics-disk-capacity.rb',
    interval    => 10,
    subscribers => 'default',
    standalone  => false,
  }

- What happened?
Notice: /Stage[main]/My_sensu::Default/Sensu::Check[metrics-disk-capacity.rb]/File[/etc/sensu/conf.d/checks/metrics-disk-capacity.rb.json]/ensure: created
Notice: /Stage[main]/My_sensu::Default/Sensu::Check[metrics-disk-capacity.rb]/Sensu_check[metrics-disk-capacity.rb]/ensure: created
Info: /Stage[main]/My_sensu::Default/Sensu::Check[metrics-disk-capacity.rb]/Sensu_check[metrics-disk-capacity.rb]: Scheduling refresh of Service[sensu-client]
Info: /Stage[main]/My_sensu::Default/Sensu::Check[metrics-disk-capacity.rb]/Sensu_check[metrics-disk-capacity.rb]: Scheduling refresh of Service[sensu-server]
Notice: /Stage[main]/Sensu::Client::Service/Service[sensu-client]: Triggered 'refresh' from 1 events
Notice: /Stage[main]/Sensu::Server::Service/Service[sensu-server]: Triggered 'refresh' from 1 events

- What did you expect to happen?
I expect to see new check in Uchiwa dashboard. Checks appears in Uchiwa dashborafter restarting sensu-api service.

- How can someone reproduce the problem?
1. Add new subscribe check.  
2. Run puppet. 
## Command used and debugging output

- What does your puppet config look like (including any hiera config)
- Is this a masterless or master based puppet setup?

## Platform and version information

- Your OS: Ubuntu 16.04
- Your Ruby version: embedded ruby
- Your version of Puppet: 4.8.1
- Your version of Sensu: 0.26.5-2 
- Your version of this module: 2.2.0

## Anything else to add that you think will be helpful?

I think sensu-api should somehow subscribe to sensu::check
https://github.com/sensu/sensu-puppet/blob/master/manifests/api/service.pp#L34-L40

**Comment by ghoneycutt** [comment]
@jeffmccune this is similar to the other issues regarding notification of services.

**Comment by ghoneycutt** [comment]
Thanks for reporting @giedriusramas 

@jeffmccune fix is in release v2.20.1
