### ISSUE TITLE
Source parameter not purged when removed from check

### ISSUE THREAD

**Issue by jaxxstorm** [sensu/sensu-puppet#601]
## Description of problem

When adding the source parameter to a check, then removing it later, the source parameter hangs around in the JSON
I expected when refreshing the JSON on the check after removing the source parameter, the source parameter remained. In order to fix this, I had to remove the check entirely

To reproduce, simply define a check:

```
sensu::check { 'test':
  command => '/bin/true'
  source => 'something'
}
```

Then update it to remove the source parameter:

```
sensu::check { 'test':
  command => '/bin/true'
}
```

## Platform and version information

- Your OS: Linux
- Your Ruby version: 2.1.1
- Your version of Puppet: 3.8.7
- Your version of Sensu: 0.25.2

**Comment by ttarczynski** [comment]
In #602 I'm adding a possibility to purge properties with `'absent'`:
```
sensu::check { 'test':
  command => '/bin/true',
  source => 'absent'
}
```

If you need to purge properties by default, we can change the default values  in [manifests/check.pp](https://github.com/ttarczynski/sensu-puppet/blob/2edd88fdd6b64c077248fb387d11221517472811/manifests/check.pp#L107-L129) from `undef` to `'absent'`. Then a property removed from `sensu::check` declaration would be also removed from JSON file.
