### ISSUE TITLE
Update repository URLs and release new module version

### ISSUE THREAD

**Issue by GhostLyrics** [sensu/sensu-puppet#606]
Please update the repository URLs according to the changes to packaging introduced with sensu 0.27.
Currently they still run with e.g. `sensu/main` instead of `trusty` for Ubuntu.

https://sensuapp.org/blog/2017/01/31/sensu-core-v0-27-0.html

**Comment by GhostLyrics** [comment]
Is there any update on this?

**Comment by jaxxstorm** [comment]
@GhostLyrics please send a pull request

**Comment by goodwolf** [comment]
See my PR for yum. I will submit another for deb repos

**Comment by law** [comment]
Any word on this for Ubuntu/debian systems?

**Comment by jaxxstorm** [comment]
@law a PR would be appreciated

**Comment by goodwolf** [comment]
Sorry humans, I was distracted by a field mouse. I will get on this.

**Comment by dzeleski** [comment]
I assume we will need to do the same for windows? 

Repo path now includes a 2012r2 folder: https://sensu.global.ssl.fastly.net/msi/2012r2/ 

https://github.com/sensu/sensu-puppet/blob/master/manifests/package.pp#L55

**Comment by dzeleski** [comment]
@jaxxstorm added some code in my fork to support windows repos: 
https://github.com/dzeleski/sensu-puppet/blob/master/manifests/package.pp#L53-L75

This uses the kernel version so we dont need to rely on stdlib methods, but would require an update to the case if a new kernel was released. Default is set to 2012r2. Any issues with this method of setting the repo?

**Comment by dzeleski** [comment]
@goodwolf The repo adds correctly for yum but the filename is incorrect so it cannot install properly. The version now includes .el(5-7). I had to append that to the sensu pkg_version var for redhat as seen here:
```
'RedHat': {
      $pkg_title = 'sensu'
      $pkg_name = 'sensu'
      $pkg_version = "${sensu::version}.el${::operatingsystemmajrelease}"
      $pkg_source = undef

      if $sensu::manage_repo {
        class { '::sensu::repo::yum': }
      }

      $pkg_require = undef
    }
```

https://github.com/dzeleski/sensu-puppet/blob/test_win_log_rotate/manifests/package.pp#L34

**Comment by jothoma1** [comment]
Any news on this ? it didnt install the latest version of sensu for me

**Comment by jothoma1** [comment]
Someone has an idea ? do i have to use @dzeleski fork ?
Thanks in advance

**Comment by dzeleski** [comment]
@jothoma1 all of my PRs were merged for this. They are using redirects in the repo itself to support the naming change on windows. For RHEL I use specific the version I want installed:

`0.27.0-1.el%{operatingsystemmajrelease}`

I cant comment on debian as I dont use it at work.

**Comment by jothoma1** [comment]
@dzeleski thanks for your response. Sorry for the questions... I'm using it in Puppet with : 

> class { 'sensu':
>   rabbitmq_host           => 'xxx',
>   rabbitmq_vhost          => 'xxx',
>   rabbitmq_password       => 'xx',
>   rabbitmq_port               => '5671',
>   rabbitmq_ssl            => true,
>   rabbitmq_reconnect_on_error => true,
>   use_embedded_ruby       => true,
>   **version => latest,**
>   redact => [ 'password', 'pass', 'api_key', 'secret' ],
> }

With version => latest, the repository (for CentOS) is not the good one and my sensu clients don't install latest updates. They are blocked on 0.26.5.

So if i understand, i have to specify the version ? 
Can you give me an example ? for centos & windows ?

Thanks a lot

**Comment by dzeleski** [comment]
@jothoma1 for windows just use the version:
`version: '0.27.1-7'`

for cent/rhel use version plus the OS major version:
hiera: `version: '0.27.1-7.el%{operatingsystemmajrelease}'`
puppet: `version => "0.27.1-7.el${facts['operatingsystemmajrelease']}",`

**Comment by cwjohnston** [comment]
I'm going to close this issue as I believe we've implemented the changes required to address these concerns. Version 2.4.0 of this module is now available on the forge.

**Comment by GhostLyrics** [comment]
Just in case someone is not aware of this: unfortunately (for me) the newer version bringing the necessary changes to apt URLs also requires Puppet 4 which makes it impossible to use for me, for the time being.

**Comment by mvasilenko** [comment]
@GhostLyrics i've hit the same issue, puppet 3 only, how can i install more recent version than 0.26.5 on Debian/Ubuntu?

**Comment by GhostLyrics** [comment]
You either
- do it manually
- try to overwrite a lot of parameters of this module
- or upgrade to Puppet 4.

I'm in the process of upgrading to Puppet 4 since I've put that off for too long anyway.
