### ISSUE TITLE
Does not install latest version

### ISSUE THREAD

**Issue by Justin-DynamicD** [sensu/sensu-puppet#622]
This module will not install beyond 0.26 due to using an out of date apt repository,  See:

[Installing Sensu Using APT](https://sensuapp.org/docs/0.28/platforms/sensu-on-ubuntu-debian.html)

Specifically, this module still points at "deb http://repositories.sensuapp.org/apt sensu main" rather than "deb https://sensu.global.ssl.fastly.net/apt $CODENAME main"

**Comment by dzeleski** [comment]
Already issues and PRs submitted for this, see here: https://github.com/sensu/sensu-puppet/issues/606

**Comment by Justin-DynamicD** [comment]
Thanks for the link.  Ill close this ticket.
