### ISSUE TITLE
Add Enterprise contact routing management

### ISSUE THREAD

**Issue by rgeniesse** [sensu/sensu-puppet#624]
I'd like to see Enterprise contact routing get added. I know that portion of the module was mostly written by one person, just wanted to get this out there.

https://sensuapp.org/docs/latest/enterprise/contact-routing.html

Seems like it would be straight forward process following mutators, handlers, etc in the manifests. I just don't have time right now to learn the `lib` section of the module.

**Comment by stevenviola** [comment]
I ran into the same issue, documented in #597. My workaround is to create a dummy handler and use the config section to define my contacts. If you have your contact json in a variable called contacts_list, you can do something like this in your manifest:

```
  sensu::handler { 'contacts':
    command => 'null',
    config  => $contacts_list,
  }
```

**Comment by rgeniesse** [comment]
Thanks for the work around. I'll try it out when I get back to re-factoring our Sensu Puppet stuff. I'll close this out as it is a dup of your request.
