### ISSUE TITLE
Getting 'cluster' error from module and then after updating getting 'heartbeat' error

### ISSUE THREAD

**Issue by Qsick** [sensu/sensu-puppet#634]
## Description of problem

- What did you do?
I'm trying to update my puppet module from version 2.1.0 to the current 2.2.0.  

- What happened?
When I downloaded the module currently on puppet forge I was getting the following error:
```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: no parameter named 'cluster' at /etc/puppetlabs/code/environments/qsick/modules/sensu/manifests/rabbitmq/config.pp:125
```
Then I went to the source on github and saw that there had been some checkins related to 'cluster' so pulled the latest from github and now am getting the following error:
```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: no parameter named 'heartbeat' at /etc/puppetlabs/code/environments/qsick/modules/sensu/manifests/rabbitmq/config.pp:126
```
- What did you expect to happen?
I expected it to work and not throw an error

- How can someone reproduce the problem?
Probably by using a similar config to what I have

## Command used and debugging output

- What does your puppet config look like (including any hiera config)
```
  class { 'sensu':
    api                         => true,
    use_embedded_ruby           => true,
    api_host                    => '127.0.0.1',
    api_password                => chomp(file('/etc/puppetlabs/puppet/files/sensu/sensu_pw')),
    api_user                    => 'sensu',
    client                      => true,
    manage_services             => true,
    manage_user                 => true,
    rabbitmq_host               => '10.10.10.35',
    rabbitmq_password           => chomp(file('/etc/puppetlabs/puppet/files/sensu/rabbitmq_pw')),
    rabbitmq_reconnect_on_error => true,
    rabbitmq_user               => 'sensu',
    redis_auto_reconnect        => true,
    redis_host                  => '10.10.10.34',
    redis_password              => chomp(file('/etc/puppetlabs/puppet/files/sensu/redis_pw')),
    redis_reconnect_on_error    => true,
    server                      => true,
    sensu_plugin_provider       => 'sensu_gem',
    version                     => 'latest',
  }
```

- Is this a masterless or master based puppet setup?
Mater based

## Platform and version information

- Your OS: Ubuntu 14.04 and 1604
- Your Ruby version: 2.3.1
- Your version of Puppet: 4.9.4
- Your version of Sensu: 26.5-2
- Your version of this module: 2.2.0 but there seem to be differences with the 2.2.0 on puppet forge and 2.2.0 on github

**Comment by dschaaff** [comment]
we get the same error on version 2.2.0 of the module

**Comment by b-0-b** [comment]
Hello all,

this can be related to https://tickets.puppetlabs.com/browse/SERVER-94

I ran into this problem when using r10k and different versions of this puppet module. We have a fairly old version of the module in production and when I try to refactor our puppet code to use the most recent version of this module in a separate r10k environment I get the same error.

You can try running `/opt/puppetlabs/bin/puppet generate types --verbose --force --environment "$ENV"` on the r10k environment.

Hope that helps,
AB

**Comment by cwjohnston** [comment]
Closing this as it seems to be a Puppet Server issue and not specific to this module.
