### ISSUE TITLE
sensu_enterprise_dashboard_api type should use `host` as namevar, not `name`

### ISSUE THREAD

**Issue by dhgwilliam** [sensu/sensu-puppet#638]
Because `name` is used as namevar, it is not possible to have multiple API endpoints represented as a single datacenter in the enterprise dashboard.

**Comment by jeffmccune** [comment]
@dhgwilliam I'm working on this presently.  Thanks for the great start, I've rebased your work on master and will build from there preserving your commits.

I'm thinking about `host` being the namevar, and I'm wondering if it's sufficient?  That is to say, have you ever run into a situation where multiple dashboards run on the same hostname or IP, but under different port numbers?

My gut tells me the fully qualified URL of the API should be the namevar.  The full URL is guaranteed to be unique for the resource.  The URL, however, leads me down the path of composite namevars.

I'll spend half an hour looking into if composite namevars are feasible, but would love your insight before I get too far down the rabbit hole.  Does a URL namevar address an issue that doesn't exist, or solve this issue once and for all?  (Or something else?)

**Comment by jeffmccune** [comment]
In progress.

**Comment by ghoneycutt** [comment]
Released in v2.14.0
