### ISSUE TITLE
Error: no parameter named 'heartbeat' at [...]/modules/sensu/manifests/rabbitmq/config.pp:126

### ISSUE THREAD

**Issue by Justin-DynamicD** [sensu/sensu-puppet#659]
Updated module from 2.2.0 -> 2.2.1
The manifest is unchanged (works in 2.2.0)
Attempting to test on Ubuntu 16.4 (likely other builds as well):

Error: no parameter named 'heartbeat' at [...]/modules/sensu/manifests/rabbitmq/config.pp:126 on Sensu_rabbitmq_config[server name]

Hopefully this list lays it out but basically the new module fails to load properly citing that it's attempting to call a missing parameter.

**Comment by jaxxstorm** [comment]
Which version of Puppet are you using?

**Comment by Justin-DynamicD** [comment]
4.10.1 (latest I think)

**Comment by xepa** [comment]
I has this same issue .. restarting the puppet-server solved the problem for me.

**Comment by jaxxstorm** [comment]
Yes, this is an old Puppet bug related to directory environments.

**Comment by rgeniesse** [comment]
FWIW, a restart of pe-puppetserver didn't solve this for me, I had to do this on my Puppetmaster:
`sudo puppet generate types --environment production`
