### ISSUE TITLE
Vagrant should have clients for other platforms

### ISSUE THREAD

**Issue by ghoneycutt** [sensu/sensu-puppet#681]
Which platforms should we add? Suggest starting with EL6, Ubuntu 16.04, Windows 2008 R2 and Windows 2012 R2.

**Comment by ghoneycutt** [comment]
@cwjohnston Which client platforms would you like to see us begin with?

**Comment by agoddard** [comment]
@ghoneycutt I think your suggested platforms are 💯

**Comment by cwjohnston** [comment]
@ghoneycutt I'm satisfied with that list 👍

**Comment by cwjohnston** [comment]
For now we can omit Win 2008 R2 to keep this manageable.

**Comment by ghoneycutt** [comment]
Platforms

- [ ] EL 6
- [ ] Ubuntu 16.04
- [ ] Windows 2012 R2

**Comment by ghoneycutt** [comment]
EL6 client in PR #689

**Comment by ghoneycutt** [comment]
Ubuntu 16 and 14 clients in PR #692

**Comment by jeffmccune** [comment]
@ghoneycutt Just as an FYI, I have the start of a Win2012r2 vagrant vm with powershell provisioning scripts as part of my work on #646

**Comment by ghoneycutt** [comment]
Excellent! I was planning on using box `opentable/win-2012r2-standard-amd64-nocm` unless you have a better idea.

**Comment by jeffmccune** [comment]
We're very closely aligned, I reached for `opentable/win-2012r2-standard-amd64-nocm` to reproduce the error in #646 

@ghoneycutt Take a look at the provisioning scripts in my https://github.com/jeffmccune/sensu-puppet/tree/646_fix_error_on_win2012r2_tests branch, they're the tricky part that I'm working through now.

I think I have it installing Puppet and running `puppet apply`.  The lesson I learned is PowerShell's CopyItem -recurse can be SUPER slow on the whole /vagrant tree.  Worked around the issue by just copying lib, manifests and templates.

**Comment by ghoneycutt** [comment]
Can you use a symlink instead of a copy?

http://lifeofageekadmin.com/create-symlinks-windows-2012-r2-server/

**Comment by jeffmccune** [comment]
Didn’t try that, trying it now.  Vagrant seems to be hanging up at the msiexec too.  Looking into both of these.

**Comment by jeffmccune** [comment]
Updated to use symlink in 43099d2, this should be good for you and #681 @ghoneycutt
