### ISSUE TITLE
Use Puppet v4's data types

### ISSUE THREAD

**Issue by ghoneycutt** [sensu/sensu-puppet#682]
This will get rid of the deprecation notices and allow us to use the improvement in Puppet v4.

https://docs.puppet.com/puppet/4.10/lang_data_type.html

**Comment by alvagante** [comment]
I can tackle this one.
Wondering if, besides using Puppet 4 data types for parameters validation, you want to use also Puppet 4.9 (4.10) data in module.
This would make the module backwards incompatible with Puppet < 4.9 , which is probably not wanted.

**Comment by ghoneycutt** [comment]
We want to maintain support for 4.9. Check out the platform list in `.travis.yml`.

**Comment by ghoneycutt** [comment]
Testing against all vagrant instances and making additions in PR #761

**Comment by ghoneycutt** [comment]
Released in v2.26.0
