### ISSUE TITLE
redis_reconnect_on_error should default to true

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-puppet#685]
## Description of problem

The `redis_reconnect_on_error` parameter currently defaults to `false`, which is inconsistent with Sensu's defaults. The official Sensu documentation has incorrectly documented this default as `false` for some time now.

Relates to https://github.com/sensu/sensu-docs/pull/601 where I've suggested a fix for the documentation.

**Comment by ghoneycutt** [comment]
The docs should be merged before this functionality.

**Comment by ghoneycutt** [comment]
Released in v2.10.0
