### ISSUE TITLE
the sensu-plugin gem is incorrectly installed with the system ruby instead of the embedded ruby

### ISSUE THREAD

**Issue by ghoneycutt** [sensu/sensu-puppet#688]
We should install the plugin and anything else using the embedded ruby and not the system ruby.

**Comment by jeffmccune** [comment]
@ghoneycutt Is the scope of this the default behavior of the module to be released to end users, or restricted to the vagrant environment, e.g. `tests/sensu-client.pp` which would need `sensu_plugin_provider => sensu_gem` added?

**Comment by jeffmccune** [comment]
[PR-694](https://github.com/sensu/sensu-puppet/pull/694) is ready for review.

**Comment by ghoneycutt** [comment]
Not just vagrant, you're on the right track here by only using the embedded ruby.

**Comment by ghoneycutt** [comment]
Released in v2.7.0
