### ISSUE TITLE
Add support for Debian 9 stretch

### ISSUE THREAD

**Issue by Debilski** [sensu/sensu-puppet#708]
Additionally, it would be helpful if the apt release specifier would be parametrised and not resolve to $::lsbdistcodename directly (see snippet below). That way one could at least use the jessie release on a Debian stretch machine.

    apt::source { 'sensu':
      ensure   => $ensure,
      location => $url,
      release  => $::lsbdistcodename, # this should be a sensu parameter
      repos    => $::sensu::repo,

**Comment by ghoneycutt** [comment]
Thanks for letting us know about Debian 9. I'm looking into adding it to our Vagrant setup now.

**Comment by ghoneycutt** [comment]
@Debilski This is not yet supported by Puppet. Until then, we will not have formal support for it. Your work around is totally valid and I'll look into implementing that.

You can watch https://tickets.puppetlabs.com/browse/PA-515 to see when Debian 9 support is added.

**Comment by Debilski** [comment]
Thanks for looking into the work-around. That puppet has no official Debian 9 support is of course a different issue altogether (though the Debian 8 version of Puppet works on 9 once you install libreadline6 from Debian 8 as well).

**Comment by deric** [comment]
@ghoneycutt FYI PA-515 has been resolved.

**Comment by ghoneycutt** [comment]
@deric We're waiting on Sensu to provide Stretch packages

https://github.com/sensu/sensu/issues/1718

**Comment by ghoneycutt** [comment]
Released in v2.47.0
