### ISSUE TITLE
Stop using private classes and the anchor pattern

### ISSUE THREAD

**Issue by ghoneycutt** [sensu/sensu-puppet#709]
The anchor pattern is deprecated. Currently we have private classes that manage pieces of the whole but do not provide value on their own. Would prefer to have fewer classes and no longer need the anchor pattern or private classes.

**Comment by ghoneycutt** [comment]
This will restructure the module enough such that existing PR's will not merge. This work should not happen until the open PR's have been closed.

**Comment by alvagante** [comment]
@ghoneycutt This also might be done during #682 
and actually, as you wrote, it's probably better to do this refactoring with large impact on code after current PRs are merged.

**Comment by ghoneycutt** [comment]
Yeah, let's hold off on this for now.

**Comment by alvagante** [comment]
@ghoneycutt I can start to work on this, based on the 682-data-types branch

**Comment by alvagante** [comment]
@ghoneycutt I'd start to work on this, don't know (maybe haven't to privileges) how to label the ticket or self assign.

**Comment by alvagante** [comment]
Works here: https://github.com/sensu/sensu-puppet/pull/763

**Comment by alvagante** [comment]
Relevant PR #763 merged. Closing issue.
