### ISSUE TITLE
unable to load facts into a newly installed puppet agent server from puppet master

### ISSUE THREAD

**Issue by kanchan1234** [sensu/sensu-puppet#719]
Action:
A newly installed Puppet server(3.6.4) is trying to load facts into puppet agent (3.8.4)
Steps;
InPuppet master
My ruby file exist inside /var/lib/puppet/lib/facter/last_run.rb
[root@sasin puppet]$ facter -p last_run
Fri Jul  7 09:11:25 CEST 2017
/etc/puppet/puppet/.conf contains pluginsync=true
Problem:
puppet agent -t ---plunginsync [in agent node]   does not create any ruby file inside /var/lib/puppet/
[root@blackcat puppet]$puppet agent -t --pluginsync
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Caching catalog for blackcat.host.mobistar.be
Info: Applying configuration version '1499407089'
Notice: This is a test notify
Notice: /Stage[main]/Main/Node[default]/Notify[This is a test notify]/message: defined 'message' as 'This is a test notify'
Notice: Finished catalog run in 0.13 seconds

**Comment by ghoneycutt** [comment]
Hi @kanchan1234 

This is not an issue with the Sensu module and seems to be an issue with your Puppet setup. Suggest posting your issues to the puppet-users mailing list or https://ask.puppet.com/questions/
