### ISSUE TITLE
Consider replacing sensu_contact (and other types) with sensu_sorted_json()

### ISSUE THREAD

**Issue by jeffmccune** [sensu/sensu-puppet#729]
This came up in the discussion of #728 which implements #597.  We're aware most of the native and defined types in the sensu module effectively pass-through data to the underlying JSON configuration files.

In an effort to make it easier and less work to maintain the Puppet module, consider making each of the defined types generic enough to pass-through configuration data as-is using sorted JSON.

The goal is to:

 - [ ] Make the sensu-puppet module future-compatible with sensu.  That is, as new configuration attributes are added, this data should be able to flow-through the defined types.  e.g. using a generic "config" attribute which accepts a Hash value.
 - [ ] Normalize the existing defined types to share behavior
 - [ ] Reduce the number of Ruby implemented custom types and providers to make it easier to add new defined types using pure Puppet code only.

**Comment by ghoneycutt** [comment]
Let's target this when we transition the module to support Sensu 2.
