### ISSUE TITLE
sensu::check resources should support cron scheduling

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-puppet#737]
## Description of problem

In Sensu 0.28 the `cron` attribute was added to the [check definition specification](https://sensuapp.org/docs/latest/reference/checks#check-attributes) as an alternative to `interval` scheduling. 

When present, the value of this attribute supersedes the `interval` attribute.

When `cron` is configured with a value, `interval` should not be required nor present in the configuration written to disk.

**Comment by ghoneycutt** [comment]
Implemented in v2.23.0
