### ISSUE TITLE
Add a test in vagrant for PR #745

### ISSUE THREAD

**Issue by ghoneycutt** [sensu/sensu-puppet#747]
Show an example of a sensu::check with ensure => false

**Comment by ghoneycutt** [comment]
@Phil-Friderici could you please have a look.

**Comment by ghoneycutt** [comment]
This is needed for Issue #782

**Comment by Phil-Friderici** [comment]
Oops, completely lost this, will have a look tomorrow.

**Comment by ghoneycutt** [comment]
Released in v2.36.0
