### ISSUE TITLE
Add client register and registration client configs

### ISSUE THREAD

**Issue by jeffmccune** [sensu/sensu-puppet#749]
Nearly identical to, #550 the client configuration should support registration attributes.

https://sensuapp.org/docs/latest/reference/clients#registration-attributes

**Comment by jeffmccune** [comment]
Putting this back in the backlog until #750 is merged into master.

**Comment by ghoneycutt** [comment]
@alvagante could you please pick this up? This will be the last of the items for us to achieve parity with the functionality in Sensu!

**Comment by ghoneycutt** [comment]
Released in v2.37.0
