### ISSUE TITLE
Create a reference implementation for provider spec tests

### ISSUE THREAD

**Issue by jeffmccune** [sensu/sensu-puppet#759]
The sensu module does a great job of exercising the behavior of Puppet classes, defined types, and the native types in the module.  The providers lack test coverage, however.

The goal of this issue is to create a reference implementation of spec tests covering the behavior of the `sensu_check` provider and the `custom` property specifically.  These spec tests will serve as a foundation to build spec tests for other providers.

The custom property has been chosen because it accepts an arbitrary map which is merged with the other properties.  This behavior is related to how all types in this module could become compatible with arbitrary attributes added in the future.

**Comment by ghoneycutt** [comment]
Thank you! This will really help us expand the provider testing.

Released in v2.28.0
