### ISSUE TITLE
Cannot manage 2008 R2 localised (french)

### ISSUE THREAD

**Issue by jothoma1** [sensu/sensu-puppet#769]
## Description of problem

- What did you do?
Using puppet module to manage my sensu clients
- What happened?
On french 2008 R2, sensu-puppet failed. I have some errors :

> Could not find group Administrators
(for this one, on a french 2008 R2, it should be **Administrateurs**

> /Stage[main]/Sensu::Package/File[C:/opt/sensu/plugins]: Could not evaluate: Puppet::Util::Log requires a message

- What did you expect to happen?
Installing sensu clients and managing them
- How can someone reproduce the problem?
Try to deploy sensu on a french 2008 R2 with puppet

## Command used and debugging output

- What does your puppet config look like (including any hiera config)
- Is this a masterless or master based puppet setup?

## Platform and version information

- Your OS:  Windows 2008 R2 French
- Your Ruby version: 2.4
- Your version of Puppet:  3.8.7
- Your version of Sensu: 1.0
- Your version of this module:

**Comment by ghoneycutt** [comment]
Thank you for this great bug report! I do not have access to Windows 2008 R2 in French. Could you please try changing this line

https://github.com/sensu/sensu-puppet/blob/master/manifests/init.pp#L700

from 

```puppet
$group = 'Administrators'
```

to 

```puppet
$group = 'Administrateurs'
```

and reporting back here to see if that fixed it. If so, we can easily solve this for you by making owner/group parameters of the sensu class.

**Comment by jothoma1** [comment]
Hi,
Yes it's working when i change to `$group = 'Administrateurs'`
I have a lot of sensu clients, some are 2012 R2 in english, some are 2008 R2 in french... 
Thanks in advance !

**Comment by alvagante** [comment]
@jothoma1 is there a fact that can reveal what's the language used on the system?

**Comment by ghoneycutt** [comment]
@alvagante instead of making an exception for the french language, let's just expose user and group as parameters with the defaults that we currently use in the code. Then the end users can change the group as they please.

**Comment by ghoneycutt** [comment]
Released in v2.36.0
