### ISSUE TITLE
Implement self.instances for all native providers

### ISSUE THREAD

**Issue by jeffmccune** [sensu/sensu-puppet#770]
Each of the native Puppet json providers lacks the `instances` class method, preventing the resource type from working with `puppet resource` and introspection.  This also prevents prefetching from working within Puppet.

While working on the providers, also refactor the use of @conf to instead used @property_hash and @property_flush.  This will bring the providers more in line with the official Puppet documentation, and other community resources like Gary's blog posts on the subject.

**Comment by ghoneycutt** [comment]
Closing as the new version of the module will likely not need this.
