### ISSUE TITLE
Modify sensu::check to use defined type sensu::write_json instead of native type sensu_check

### ISSUE THREAD

**Issue by jeffmccune** [sensu/sensu-puppet#783]
In an effort to support arbitrary configuration scopes for plugins and extensions as mentioned in #764, the goal of this card is to implement a new parameter to the sensu::check defined type.  This parameter needs a reasonable name (`config` is too generic and over-loaded).  The desired behavior is  to have the new parameter merged with all other parameters to produce a single, top-level JSON object written to the filesystem using sensu::write_json.

For the purposes of the change, two scopes are considered.  All configuration in-scope is nested under `checks.mycheck` for a check named `mycheck`.  All configuration out-of-scope is outside the nested `checks.mycheck` map.  All out-of-scope configuration is managed by the new parameter, all in-scope configuration is managed by the existing parameters.

The new parameter is akin to the existing `custom` parameter, just at the top level instead of nested inside the check configuration scope.

**Comment by ghoneycutt** [comment]
How about `content` since that's what we are effectively setting with the data. Eventually `custom` and the other parameters will go away and all data will use the single parameter. We can use the struct data type for validation.

**Comment by jeffmccune** [comment]
> How about `content`

I like it.  The best I came up with was `additional` and content is way better.

**Comment by ghoneycutt** [comment]
Released in v2.32.0
