### ISSUE TITLE
Sensu Enterprise API SSL attributes are incorrectly configured

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-puppet#784]
## Description of problem

- What did you do?

Configured` api_ssl_port`, `api_ssl_keystore_file` and `api_ssl_keystore_password` parameters

- What did you expect to happen?

Expected rendered configuration to match [documented Sensu Enterprise SSL attributes](https://sensuapp.org/docs/1.0/enterprise/api.html#ssl-attributes-example). e.g.

```
{
  "api": {
    "ssl": {
      "port": 4568,
      "keystore_file": "/etc/sensu/api.keystore",
      "keystore_password": "secret"
    }
  }
}
```

- What happened?

API SSL parameter values were rendered under `api` scope but do not match documented configuration attributes:

```
{
  "api": {
    "ssl_port": 4568,
    "ssl_keystore_file": "/etc/sensu/api.keystore",
    "ssl_keystore_password": "secret"
  }
}
```

- How can someone reproduce the problem?

Use the module to configure Sensu Enterprise with `api_ssl_port`, `api_ssl_keystore_file` and `api_ssl_keystore_password` parameters

## Anything else to add that you think will be helpful?

It appears that the specs for this module feature don't align with the documented Sensu Enterprise API configuration specifications.

**Comment by ghoneycutt** [comment]
Thanks @cwjohnston for the great bug report.

Released in v2.30.1
