### ISSUE TITLE
sensu::plugin does not work on windows without specifying install_path

### ISSUE THREAD

**Issue by ghoneycutt** [sensu/sensu-puppet#786]
sensu::plugin::install_path defaults to `/etc/sensu/plugins`. While you can set that if you use windows, the module should do the right thing.

We should default `install_path` to undef and in the defined type have a conditional that sets `install_path_real` to use a default if the value is undef.

This needs a `sensu::plugin` addition to `tests/sensu-client-windows.pp` where install_path is not specified so it can be validated.

**Comment by Phil-Friderici** [comment]
Used the same logic as in main class [1] to specify install_path.
Changed the call of sensu::plugin in the main class to not specify install_path anymore.

Will continue to work on the vagrant part to validate install_path in ```tests\sensu-client-windows.pp```.

[1] https://github.com/sensu/sensu-puppet/blob/v2.30.1/manifests/init.pp#L487-L490

**Comment by ghoneycutt** [comment]
Released in v2.31.0
