### ISSUE TITLE
minimum apt version wall

### ISSUE THREAD

**Issue by Justin-DynamicD** [sensu/sensu-puppet#788]
##minimum apt version wall
As of 2.5.0 and later,  sensu-sensu now requires puppetlabs-apt > 4.0.0.  This is a breaking requirement change for me (and I assume other puppet users) as there are LOTS of modules out there that still have a <3.0.0 requirement putting us in a "which module is more important" scenario.   Some modules are even useful/critical for sensu itself like  puppet-grafana (>=2.1.0 < 3.0.0) and puppetlabs-rabbitmq (>=1.8.0 <3.0.0).  

Was the jump to 4.0 needed?

**Comment by SergK** [comment]
@Justin-DynamicD Hi, I've raised the same question https://github.com/sensu/sensu-puppet/issues/781 , so unfortunately, as workaround, I forked repo and revert the change which introduced this change.

**Comment by Justin-DynamicD** [comment]
the response of "wont fix" seems poorly thought through.  If the devs are reading this I'd like to once again point out that the following module is basically _needed_ to manage sensu with puppet yet cannot coexist with this module anymore:

puppetlabs-rabbitmq

Won't fix basically means "this module is broken until rabbitmq folks update".  That's a pretty big issue.

**Comment by ghoneycutt** [comment]
Perhaps there is some confusion as @Justin-DynamicD stated that we require apt > 4 though it is actually >= 4

https://github.com/sensu/sensu-puppet/blob/master/metadata.json#L64

This is supported by puppetlabs-rabbitmq

https://github.com/voxpupuli/puppet-rabbitmq/blob/master/metadata.json#L51

**Comment by ghoneycutt** [comment]
Created https://github.com/voxpupuli/puppet-grafana/pull/53 to help with the grafana module.

**Comment by madAndroid** [comment]
We're experiencing this as well... according to the style guide, soft dependencies shouldn't be declared in the `metadata.json` => https://docs.puppet.com/puppet/latest/style_guide.html#dependencies.

Since this is a dependency only for Debian `osfamily`, is this regarded as a hard depedency?

**Comment by ghoneycutt** [comment]
It is on Debian :>

I agree that it's not a hard dependency as folks running this on Windows certainly don't need to install the apt module.

**Comment by ghoneycutt** [comment]
Created #791 to remove apt from the metadata as a dependency.

**Comment by ghoneycutt** [comment]
@Justin-DynamicD did you see my notes above? I think you might be running an old version of rabbitmq.

**Comment by Justin-DynamicD** [comment]
Perhaps the notes are out of date, but if you hit the site:
https://forge.puppet.com/puppetlabs/rabbitmq/dependencies

"puppetlabs/apt (>=1.8.0 <3.0.0)".

So I'm basing my concern there.

**Comment by SergK** [comment]
Regarding rabbitmq, yes, they bump apt module version, but haven't `release it` yet, so it's on master branch only

**Comment by ghoneycutt** [comment]
We dropped apt as a hard dependency in v2.31.0

**Comment by madAndroid** [comment]
@ghoneycutt - awesome, thank you
