### ISSUE TITLE
Absolute path set for rabbitmq ssl certs

### ISSUE THREAD

**Issue by sblatt** [sensu/sensu-puppet#798]
https://github.com/sensu/sensu-puppet/blob/438fbaa2e3d92db192bce1c83afb97d2c445d059/manifests/rabbitmq/config.pp#L41
should include ${ssl_dir} wherever /etc/sensu is used. Might mainly affect Windows.

Affects multiple occurrences.

**Comment by ghoneycutt** [comment]
Released in v2.35.0
