### ISSUE TITLE
transport.json not created when transport_type = rabbitmq

### ISSUE THREAD

**Issue by htallur** [sensu/sensu-puppet#809]
## Description of problem
transport.json is not created 

incorrect logic in transport.pp
-----------
  if $::sensu::transport_type != 'redis' {
    $ensure = 'absent'
  } else {
    $ensure = 'present'
  }
-------------

ensure = 'absent',  when transport_type = 'redis' in transport.pp

**Comment by alvagante** [comment]
@htallur what's the expected behaviour? I suppose that a transport.json has to be created in any case , both with redis and rabbitmq transport .

I can eventually add a parameter $ensure to the sensu::transport class, to allow users to eventually force the removal of transport.json

**Comment by ghoneycutt** [comment]
Released in v2.37.0
