### ISSUE TITLE
Add support for Windows 10

### ISSUE THREAD

**Issue by benh57** [sensu/sensu-puppet#822]
## Description of problem

- What did you do?
Attempt to install sensu client on windows 10 using the puppet module.

- What happened?

Fails to install from  https://repositories.sensuapp.org/msi/10/sensu-1.0.0-1-x64.msi

This is because the module uses the os.major version as the url dir which does not exist on the sensu repository.

## Platform and version information

- Your OS: Windows 10 Enterprise VL
- Your version of Puppet: 5.2.0
- Your version of Sensu: 1.0.0
- Your version of this module: 2.35.0

## Anything else to add that you think will be helpful?

Locally i've fixed this by doing:

        if $os_release == '10' {
          $pkg_url_dir = '2016'
        } else {
          # e.g. '2012 R2' => '2012r2'
          $pkg_url_dir = regsubst($os_release, '^(\d+)\s*[rR](\d+)', '\\1r\\2')
        }
I can submit a PR for this if you like.

**Comment by ghoneycutt** [comment]
Thank you for reporting this! We do not currently support Windows 10, though would be glad to do so. In order for us to support it, we would need it to work under Vagrant so it could be tested.

Is Windows 10 newer than 2012? That seems to be how it is differentiated at https://sensuapp.org/downloads

Should it just use the 2012r2 package?

There would need to be `win10-client` added, similar to `win2012r2-client` at https://github.com/sensu/sensu-puppet/blob/master/Vagrantfile#L137-L156

Not sure which vagrant box we should use. This one maybe? https://app.vagrantup.com/souldonut/boxes/win_10_vbox_nocm

**Comment by benh57** [comment]
Yes, I am testing using my own Vagrantfile and windows 10 box. But i can try out the one that comes with the module if i get time. 

 I thought windows 10 was be closer to 2016 than 2012r2 so I chose that one, but you're right they don't seem to link to it on the downloads page. I'm not sure of the differences on the sensu side.  They have 2016 MSI's published here: https://repositories.sensuapp.org/msi/2016/

**Comment by benh57** [comment]
FWIW , it looks like this also breaks on Windows 7.  It tries to get the pkg from /msi/7 which doesn't exist.

**Comment by benh57** [comment]
I'm not really sure why they have OS-specific packages for Windows. It should work on any.

**Comment by ghoneycutt** [comment]
@agoddard Can you speak to the OS specific packages for Windows?

**Comment by agoddard** [comment]
@ghoneycutt @benh57 we had to split up newer & older versions of Windows due to .NET dependency differences

**Comment by benh57** [comment]
Surely the installer could detect and handle that?

**Comment by agoddard** [comment]
@benh57 it definitely would be nice if it could. I've opened an issue on the Sensu-omnibus project to see if it's possible: https://github.com/sensu/sensu-omnibus/issues/234

**Comment by ghoneycutt** [comment]
Waiting for feedback from https://github.com/sensu/sensu-omnibus/issues/234

**Comment by ghoneycutt** [comment]
Windows 10 is not officially supported. Suggest using the code above provided by @benh57 in your profile for sensu.
