### ISSUE TITLE
Sensu Enterprise Service Not Reloading After Checks

### ISSUE THREAD

**Issue by csoleimani** [sensu/sensu-puppet#827]
- What did you do?
**Adding a new check or change a check**
- What happened?
check definition changed, but the sensu-enterprise was not restarted/reloaded
**- What did you expect to happen?**
**the sensu-enterprise service to get restarted/reloaded**

- How can someone reproduce the problem?
**add a new check or change an existing check with sensu-enterprise**

## Command used and debugging output

- What does your puppet config look like (including any hiera config)
```
  class { '::sensu':
    enterprise                   => true,
    enterprise_version           => $::sensu::enterprise_version,
    enterprise_dashboard         => true,
    enterprise_dashboard_version => $::sensu::enterprise_dashboard_version,
    enterprise_dashboard_host    => 'localhost',
    enterprise_dashboard_port    => 3000,
    enterprise_dashboard_refresh => '5',
    enterprise_user              => 'cameron',
    enterprise_pass              => password,
    install_repo                 => true,
    log_level                    => $log_level,
    purge                        => {
      config => true,
    },
    rabbitmq_cluster             => $rabbitmq_cluster,
    redis_db                     => $redis_db,
    redis_host                   => $redis_host,
    version                      => $client_version,
  }
```
- Is this a masterless or master based puppet setup?
**master**

## Platform and version information

- Your OS: 
**Debian 8**
- Your Ruby version:
**ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]**
- Your version of Puppet: 
**2017.2.2 - Enterprise**
- Your version of Sensu: 
**1.1.0**
- Your version of this module: 
**2cebbdef163bf12d66b59e8b27aa58bd10559219**

## Anything else to add that you think will be helpful?

https://github.com/sensu/sensu-puppet/pull/828

**Comment by ghoneycutt** [comment]
We've released a fix for this. Please try the newest release of the module and re-open if this is still an issue.

Thanks @csoleimani
