### ISSUE TITLE
Feature Request: Ability to manage userOptions in dashboard.json

### ISSUE THREAD

**Issue by rgeniesse** [sensu/sensu-puppet#842]
## Description of feature

Feature request for the ability to manage userOptions in dashboard.json.

## Anything else to add that you think will be helpful?
While only called out in the Uchiwa (open source dashboard) documentation, I have shown on my own Enterprise Dashboard test server that adding these options are honored. The example here is `requireSilencingReason` only as that is all I am using now. The other options noted in the Uchiwa documentation at the end may be useful for others.

`{
  "dashboard": {
    "usersOptions": {
      "requireSilencingReason": true
    },
    "host": "0.0.0.0",
    "port": 8443,
    "refresh": 60,`

Uchiwa doc:
https://docs.uchiwa.io/getting-started/configuration/

**Comment by ghoneycutt** [comment]
Thanks for reporting! This might be more useful in the Uchiwa project itself at https://github.com/Yelp/puppet-uchiwa

**Comment by rgeniesse** [comment]
Yes, I was sorta torn where to actually open it as the feature would span both projects. Uchiwa could use it, but this module covers the Sensu Enterprise Dashboard configuration already so felt like here was the best spot for my use case.

I don't know enough about these modules to know if it is solved in one place, that means it could be brought over to the other easily.

I'll gladly open one there too, but any contribution there would not be useful for Enterprise users. At least in my case, I don't have Uchiwa managed by a separate module or even installed standalone.

**Comment by ghoneycutt** [comment]
The `sensu::enterprise::dashboard` class should allow a hash of user defined data that is added to the `dashboard.json` config. This should work like the `custom` attribute for `sensu::check`.

https://github.com/sensu/sensu-puppet/blob/master/manifests/check.pp#L78

**Comment by ghoneycutt** [comment]
Released in v2.54.0

**Comment by ninjasloth22** [comment]
Can you confirm this was implemented ? I don't see it in the code in version v2.58.0

**Comment by treydock** [comment]
@ninjasloth22 It appears this was not implemented.

**Comment by ghoneycutt** [comment]
@treydock can you please investigate
