### ISSUE TITLE
switch from puppetlabs/rabbitmq to puppet/rabbitmq

### ISSUE THREAD

**Issue by ghoneycutt** [sensu/sensu-puppet#844]
Our docs and tests use puppetlabs/rabbitmq which is deprecated in favor of puppet/rabbitmq (Vox Pupuli)

**Comment by ghoneycutt** [comment]
Hi @alvagante this is a high priority for us

**Comment by alvagante** [comment]
@ghoneycutt ok, will give it s look in the weekend

**Comment by alvagante** [comment]
@ghoneycutt this https://github.com/sensu/sensu-puppet/pull/848 should make rabbitmq work on the local vagrant environment, with puppet/rabbitmq module

**Comment by alvagante** [comment]
@ghoneycutt suppose this one can be closed now

**Comment by ghoneycutt** [comment]
Released in v2.42.0
