### ISSUE TITLE
Not all Sensu Enterprise Dashboard options are available

### ISSUE THREAD

**Issue by ghoneycutt** [sensu/sensu-puppet#866]
## Description of problem

We are missing at least `auth` and `oidc` from the `sensu::enterprise::dashboard` class.

https://sensuapp.org/docs/1.2/enterprise/dashboard.html#dashboard-attributes

**Comment by ghoneycutt** [comment]
@treydock Could you please have a look?

**Comment by treydock** [comment]
@ghoneycutt Ya I'll take a look.

**Comment by ghoneycutt** [comment]
Released in v2.48.0
