### ISSUE TITLE
Custom types should not log passwords and other sensitive information

### ISSUE THREAD

**Issue by treydock** [sensu/sensu-puppet#886]
## Description of problem

Currently several custom types will log output that is sensitive such as passwords

```
  Notice: /Stage[main]/Sensu::Rabbitmq::Config/Sensu_rabbitmq_config[centos-7-x64]/password: defined 'password' as 'secret'
```

It's not unheard of for non-admins to have access to system logs via tools like Splunk so would be good to avoid writing passwords to logs.

## Command used and debugging output

Observed in acceptance tests.

## Platform and version information

- Your OS: CentOS 7
- Your version of Puppet: 4.10.10
- Your version of this module: 2.50.0

**Comment by ghoneycutt** [comment]
Fixed for Sensu v1. Re-opening until this is also applied to Sensu v2.

**Comment by treydock** [comment]
For Sensu v2 the user passwords are already suppressed in `sensu_user` type.  The `agent.yml` passwords can have diff turned off via `sensu::agent::show_diff` added in #1042
