### ISSUE TITLE
Vagrant fails for win2012r2-client-chocolatey

### ISSUE THREAD

**Issue by ghoneycutt** [sensu/sensu-puppet#893]
See #891

**Comment by treydock** [comment]
I'm not finding sensu on chocolatey website

https://chocolatey.org/packages?q=sensu
https://chocolatey.org/packages?q=sensu-client

Found a rejected package: https://chocolatey.org/packages/sensu-client

**Comment by ghoneycutt** [comment]
@portertech You know where the chocolatey packages are?

**Comment by ghoneycutt** [comment]
Asking for chocolatey packages in https://github.com/sensu/sensu/issues/1874

**Comment by ghoneycutt** [comment]
This does not seem like it is going to be addressed by Sensu 1 as focus is on moving to Sensu 2.
