### ISSUE TITLE
Feature Request: Support for disabling the TCP/UDP Socket entirely

### ISSUE THREAD

**Issue by jaredledvina** [sensu/sensu-puppet#902]
New in Sensu 1.3.0 is the ability to disable the TCP/UDP socket entirely: https://github.com/sensu/sensu/blob/master/CHANGELOG.md#130---2018-03-09

Currently, it looks like this module, hard codes configuring the TCP/UDP socket here: https://github.com/sensu/sensu-puppet/blob/master/manifests/client.pp#L102-L105

Ideally, it'd be setup similar to the `http_socket` allowing it to be completely disabled.

**Comment by ghoneycutt** [comment]
So setting client_bind and client_port to undef does not work, instead the socket_config should be missing entirely, is that correct?

**Comment by ghoneycutt** [comment]
Released in v2.53.0
