### ISSUE TITLE
sensu2 acceptance tests timing out in travis-ci

### ISSUE THREAD

**Issue by treydock** [sensu/sensu-puppet#918]
sensu2 acceptance tests for some of the Debian and Ubuntu tests are timing out.

**Comment by ghoneycutt** [comment]
PR #919 was merged though leaving this open as it is still a problem.

**Comment by treydock** [comment]
@ghoneycutt PR #929 helps but doesn't guarantee no timeouts.  There is just something inherently slow with Debian 8 and Ubuntu 16.04 that I can't explain.  So far the simplest solution seems to be bundling multiple puppet manifests into one so that fewer invocations of `puppet apply` have to be executed.  Another solution could be to build custom docker images that already have Puppet bootstrapped but less flexible.

**Comment by treydock** [comment]
I'm going to update acceptance tests to take environment variable `BEAKER_sensu_full` that when has value like `true` or `yes` will trigger acceptance tests to test types/providers.  If that environment variable is not set or undefined only the agent and backend tests will run.  This environment variable approach will be easy to allow ad-hoc testing of other platforms if necessary as well as make it clear which platform in Travis-CI is running the full test suite.

**Comment by treydock** [comment]
@ghoneycutt Closing as was resolved with #935
