### ISSUE TITLE
sensu2 admin password handling is incorrect

### ISSUE THREAD

**Issue by treydock** [sensu/sensu-puppet#928]
## Description of problem

If this module is used for the first time with a non-default admin password the `sensuctl configure` step will fail.

I do not think a solution will be possible until the `sensu_user` type can be created at which point that type and provider will have to update the admin user and run `sensuctl configure`.  The `sensuctl configure` used by `backend.pp` needs to use the default password if first time being invoked.

## Command used and debugging output

Below output is a fresh install.

```
[root@sensu-backend ~]# sensuctl configure -n --url http://localhost:8080 --username admin --password foobar

Error: unable to authenticate with error: Request unauthorized

[root@sensu-backend ~]# sensuctl configure -n --url http://localhost:8080 --username admin --password 'P@ssw0rd!'
[root@sensu-backend ~]# sensuctl user list
  Username     Roles     Enabled
 ────────── ─────────── ─────────
  admin      admin       true
  agent      agent       true
  sensu      read-only   true
```

## Platform and version information

- Your OS: EL7
- Your Ruby version: 2.4
- Your version of Puppet: puppet-agent 5
- Your version of Sensu: sensu 2 nightlies
- Your version of this module: sensu2 branch

**Comment by ghoneycutt** [comment]
Fixed by #1011
