### ISSUE TITLE
sensu2 acceptance tests failing for Debian and Ubuntu

### ISSUE THREAD

**Issue by treydock** [sensu/sensu-puppet#943]
## Description of problem

Acceptance tests for sensu2 are failing for all Debian and Ubuntu except Ubuntu 18.04

I think we're hitting this bug: https://tickets.puppetlabs.com/browse/MODULES-6543

I don't know why we didn't see this sooner.  Puppetlabs just released version 5.0.0 of puppetlabs/apt so either that introduced a regression or the docker images we test against were updated on docker hub.

**Comment by treydock** [comment]
Error from Puppet:

```
Notice: /Stage[main]/Apt::Update/Exec[apt_update]/returns: E: The method driver /usr/lib/apt/methods/https could not be found.
  Notice: /Stage[main]/Apt::Update/Exec[apt_update]/returns: E: Failed to fetch https://packagecloud.io/sensu/nightly/debian/dists/stretch/InRelease
  Notice: /Stage[main]/Apt::Update/Exec[apt_update]/returns: E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by ghoneycutt** [comment]
apt is a soft dependency, since it is only required for compilation on systems that use apt. Because of this, I dont think it should be in the metadata.json until it has a section for soft dependencies.

**Comment by treydock** [comment]
Tested by pinning to puppetlabs/apt 4.5.1 and the acceptance tests pass.  

I can update #936 to specify versions we support or we can document having to install `apt-transport-https` with newer puppetlabs/apt.

This commit removed `apt-transport-https` but not clear why https://github.com/puppetlabs/puppetlabs-apt/commit/ca31cab98756aa2ed40cc4dc717ab6bbdb3e2afe#diff-a3efcdc2c485949d50da5816e90d89de

We can add `apt-transport-https` during acceptance tests for osfamily=Debian and just document that step is necessary for new apt modules?

**Comment by ghoneycutt** [comment]
Let's not worry about the documentation as puppetlabs/apt v5 should be patched soon, instead we'll just say we work with v4. We don't have to entice people to upgrade to a broken version of puppetlabs/apt
