### ISSUE TITLE
Default `vagrant up` brings up too many systems

### ISSUE THREAD

**Issue by ghoneycutt** [sensu/sensu-puppet#971]
## Description of problem

Ran `vagrant up` and it brings up an entire sensu backend cluster. For basic usage and testing, we do not need that many systems to be running. This can be a detraction for users with limited resources.

`sensu-backend-peer1` and `sensu-backend-peer2` should not start by default. There should be documentation that explains that these should be started if a cluster is wanted.

**Comment by treydock** [comment]
Right now the Vagrant environment doesn't actually setup sensu-backend as a cluster.  Doing something like `vagrant up sensu-backend sensu-backend-peer1 sensu-backend-peer2` would just bring up 3 standalone sensu-backend boxes.  Do we want to document this behavior or change the behavior to support provisioning a cluster via Vagrant?

**Comment by ghoneycutt** [comment]
autostart is set to true on the backend systems and should not be. Having documentation on how to bring up the other backends and create a cluster would be well received.
