### ISSUE TITLE
Re-evaluate parallel execution of acceptance tests

### ISSUE THREAD

**Issue by treydock** [sensu/sensu-puppet#981]
## Description of problem

It seems that if the parallel bits of acceptance tests fail the test will just hang and eventually time out rather than fail fast.  Initially parallel execution was used speed up tests but now that's mostly unnecessary because the long running tests only run for EL7 docker container.

Screen eventually gets flooded with this:

```
D, [2018-09-18T18:18:29.102433 #8877] DEBUG -- : Waiting for child processes.
```

**Comment by ghoneycutt** [comment]
Released in v2.56.0
