### ISSUE TITLE
Support Puppet 6

### ISSUE THREAD

**Issue by treydock** [sensu/sensu-puppet#983]
## Description of problem

Looks like Puppet 6.0.0 was released today which is why suddenly facter 3.12.0 broke all tests.  Should be easy to support Puppet 6 tests once #982 is merged.

**Comment by treydock** [comment]
@ghoneycutt What acceptance tests should we target for puppet6 collection?  I was thinking at minimum the one with `BEAKER_sensu_full=yes`, but that won't fully validate the classes.  Should we test all supported OSes?

**Comment by bastelfreak** [comment]
If you're interested: on Vox Pupuli we run the full spec tests and acceptance tests on puppet5 and on puppet6.

**Comment by ghoneycutt** [comment]
Sensu v1 needs to drop support for Puppet 4 since Puppet 6 is out as well as use the current versions of ruby for Puppet 5 (2.4.4).

**Comment by ghoneycutt** [comment]
We are not changing the interface to the software, so no. It will likely keep working with v4, though not a supported platform. We support the current major release and the last one.

**Comment by ghoneycutt** [comment]
Do not close until PR #986 and #988 are both closed.
